Repository dlang/phobos, pull requests merged in 2018-03, with the labels that each got.

#6218 Adds Typedef.toString()
  std/typecons.d
Labels: Enhancement, auto-merge

#6242 [ASan] Handle the (invalid) return value of posix_memalign
  std/experimental/allocator/mallocator.d
Labels: auto-merge

#6239 Update lockingTextWriter docs
  std/stdio.d
Labels: auto-merge, documentation

#6211 fix issue 18501 - randomShuffle and partialShuffle should return their input argument
  std/random.d
Labels: Enhancement, auto-merge

#6243 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/compile-time-format-optimized.dd
  changelog/fix18397.dd
  changelog/nullable-class.dd
  changelog/std-algorithm-iteration-substitute.dd
  changelog/std-bigint-divmod.dd
  changelog/std-bigint-getDigit.dd
  changelog/std-exception-enforce.dd
  changelog/std-experimental-all.dd
  changelog/std-experimental-allocator-rciallocator.dd
  changelog/std-experimental-allocator-rcisharedallocator.dd
  changelog/std-file-readText.dd
  changelog/std-parallelism-fold.dd
  changelog/std-range-nullsink.dd
  changelog/std-range-slide.dd
  changelog/std-string-strip.dd
  changelog/std-traits-issomestring.dd
  changelog/toString.dd
  std/stdio.d
Labels: auto-merge

#6241 Prefer an appender to a dynamic array
  std/array.d
Labels: auto-merge, optimization

#6240 Remove an unnecessary index
  std/conv.d
Labels: Trivial, auto-merge

#6244 [dmd-cxx] Backport PIC logic from stable into dmd-cxx
  posix.mak
Labels: Trivial

#6224 Use baseName to also skip leapseconds file in subfolders
  std/datetime/timezone.d
Labels: auto-merge

#6245 Fix strerror usage in uClibc version
  std/exception.d
  std/socket.d
Labels: auto-merge

#4885 Fix issue 13642 - Change of length reallocates without notifying GC
  std/container/array.d
Labels: Bug Fix, auto-merge, needs review

#6238 Minor optimization for byDchar for wchar[] / byWchar for dchar[]
  std/utf.d
Labels: auto-merge

#6248 AA key needs at least one data field
  std/traits.d
Labels: Blocking Other Work, Trivial, auto-merge

#6110 Fix issue 18134 - BitArray right shift broken if length is multiple of 8*size_t.sizeof
  std/bitmanip.d
Labels: Bug Fix, auto-merge

#6249 Added writer version of toString to std.datetime.interval.Interval
  std/datetime/interval.d
Labels: Enhancement

#6228 Fix digits grouping in formatValue() for floating point numbers
  changelog/std-format-fixDigitGrouping
  std/format.d
Labels: Bug Fix, auto-merge

#6258 Add website link to author name for Jonathan M Davis.
  std/array.d
  std/ascii.d
  std/bitmanip.d
  std/datetime/date.d
  std/datetime/interval.d
  std/datetime/package.d
  std/datetime/stopwatch.d
  std/datetime/systime.d
  std/datetime/timezone.d
  std/exception.d
  std/file.d
  std/range/interfaces.d
  std/range/package.d
  std/range/primitives.d
  std/string.d
  std/system.d
  std/utf.d
Labels: Trivial, auto-merge, documentation

#6234 fix issue 18519 freebsd 11 + phobos + curl, timing out
  std/net/curl.d
Labels: Bug Fix, auto-merge

#6256 Fix Issue 18182 - std.uri should be usable in @safe
  std/uri.d
Labels: Enhancement, attributes, auto-merge

#6252 Fix Issue 18158 - std.file.getcwd should be usable in @safe
  std/file.d
Labels: Enhancement, attributes, auto-merge

#6265 Fix issue with benchmark unit test when compiling with optimizations.
  std/datetime/stopwatch.d
Labels: auto-merge

#6260 Add badge to Bugzilla
  README.md
Labels: auto-merge

#6112 Fix issue 18133 - improve docs and add code examples for BitArray constructors
  std/bitmanip.d
Labels: auto-merge

#6266 [TRIVIAL] std.experimental.logger...: Fix -dip1000 compilable issues
  std/experimental/logger/core.d
  std/experimental/logger/filelogger.d
Labels: Trivial, auto-merge

#6251 Fix Issue 18168 - std.base64.encode output ranges @safe
  std/base64.d
Labels: Enhancement, attributes, auto-merge

#6263 Fix Issue 18565 - std.regex Captures opAssign returns void
  std/regex/package.d
Labels: Bug Fix, auto-merge

#6261 std.traits.FieldNameTuple: clarify documentation and add testing for classes
  std/traits.d
Labels: auto-merge

#6156 Fix Issue 8341 - topN(zip()) doesn't work
  std/algorithm/mutation.d
  std/algorithm/sorting.d
Labels: Enhancement, auto-merge

#6269 Fix CircleCI
  std/algorithm/sorting.d
Labels: Trivial, auto-merge

#6247 Fix Issue 18548 - std.format ignores templated toString if another to…
  std/format.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#6255 Fix Issue 18166 - std.array.replace should be usable in @safe for dst…
  std/array.d
Labels: Enhancement, attributes, auto-merge

#6271 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/format.d
  std/regex/package.d
Labels: Bug Fix, auto-merge

#6041 Fix Issue 17961 - std.uni does not compile with -unittest -dip1000
  std/uni.d
Labels: Blocking Other Work, Bug Fix

#6235 Added writer overload of toString to Appender
  std/array.d
  std/uni.d
Labels: Enhancement, auto-merge

#6273 Add writer overload to BitArray
  std/bitmanip.d
Labels: Enhancement, auto-merge

#6275 std.math: fix feqrel for ibmExtended floats.
  std/math.d
Labels: auto-merge

#6276 Remove a cast from std.process
  std/process.d
Labels: Trivial, auto-merge

#6279 Fix Issue 18174 - std.math.equalsDigit should be usable in @safe
  std/math.d
Labels: Enhancement, Trivial, auto-merge

#6280 Reduce size of slow testcase in std.algorithm.setops
  std/algorithm/setops.d
Labels: auto-merge

#6144 Use __traits(isSame) for min,maxElement
  std/algorithm/searching.d
Labels: Enhancement, auto-merge

#6285 Fix Ddoc error in the quickoverview of std.algorithm.sorting
  std/algorithm/sorting.d
Labels: Trivial, auto-merge, documentation

#6283 std.algorithm fix typo in reference to std.range.SortedRange
  std/algorithm/searching.d
Labels: Trivial, auto-merge, documentation

#6284 std.algorithm: remove mismatch from the std.algorithm.searching overview
  std/algorithm/searching.d
Labels: Trivial, auto-merge, documentation

#6287 Add .dd extension to the fixDigitGrouping changelog entry
  changelog/std-format-fixDigitGrouping.dd
Labels: Trivial, auto-merge

#6290 Fix Issue 18624 - wrong behavior of getSymbolsByUDA if one of the symbols having th…
  std/traits.d
Labels: Bug Fix

#6293 biguintcore: immutability cannot be inferred for sub() and add()
  std/internal/math/biguintcore.d
Labels: Blocking Other Work

#6277 Remove the empty std.digest.digest site
  posix.mak
  std/ascii.d
  std/digest/digest.d
Labels: Trivial, auto-merge, documentation

#6289 Simplify implementation of errnoEnforce
  std/exception.d
Labels: Trivial, auto-merge

#6175 Added SharedRegion
  std/experimental/allocator/building_blocks/region.d
Labels: Bug Fix

#6305 biguintcore: more immutability casts needed
  std/internal/math/biguintcore.d
Labels: Blocking Other Work, auto-merge

#6278 posix.mak: module-specific -dip25/1000 for someModule.test and unitte…
  dip1000.mak
  posix.mak
Labels: auto-merge

#6298 Added public example for assumeSorted
  std/range/package.d
Labels: auto-merge, documentation

#6296 Add public examples to std.datetime.package and enable dscanner check
  .dscanner.ini
  std/datetime/package.d
Labels: auto-merge, documentation

#6297 Fix documentation for Take, Cycle, and Choose
  std/range/package.d
Labels: auto-merge, documentation

#6302 fix issue 18631 - Allow choice to work with const arrays
  std/random.d
Labels: Bug Fix, auto-merge

#6299 Add documentation for StoppingPolicy and Fix docs for Lockstep
  std/range/package.d
Labels: auto-merge, documentation

#6300 Add examples for TransverseOptions, isTwoWayCompatible, SearchPolicy
  std/range/package.d
Labels: documentation

#6308 Add examples to std.datetime.date and enable dscanner check
  .dscanner.ini
  std/datetime/date.d
Labels: auto-merge, documentation

#6309 [Trivial] Remove std.stdio imports from std.algorithm.mutation
  std/algorithm/mutation.d
Labels: Trivial, auto-merge

#6312 Enable dscanner check for std.range.package
  .dscanner.ini
Labels: auto-merge, automation

#6313 Add public example for UUID and enable DScanner check
  .dscanner.ini
  std/uuid.d
Labels: documentation

#6315 Add examples to std.range.primitives and enable dscanner check
  .dscanner.ini
  std/range/primitives.d
Labels: documentation

#6314 Add public examples to std.uri + enable DScanner check
  .dscanner.ini
  std/uri.d
Labels: auto-merge, documentation

#6316 Added examples and docs to qualifier templates in std.traits
  std/traits.d
Labels: auto-merge, documentation

#6311 Split-up .dscanner.ini blacklists into multiple lines
  .dscanner.ini
  posix.mak
Labels: auto-merge, automation

#6319 dip1000.mak: Lift std.container.dlist
  dip1000.mak
Labels: auto-merge

#6321 Fix unrelated DAutoTest diff changes
  std/exception.d
Labels: Enhancement, auto-merge

#6304 Fix issue 18634 - support for delegate comparators in rbtree
  std/container/rbtree.d
Labels: Bug Fix, auto-merge

#6268 Cache and reuse std.regex engine to speed repeated matching
  std/regex/internal/backtracking.d
  std/regex/internal/ir.d
  std/regex/internal/parser.d
  std/regex/internal/thompson.d
  std/regex/package.d
Labels: Enhancement, auto-merge, optimization

#6317 Combine docs for std.range.repeat
  std/range/package.d
Labels: auto-merge, documentation

#6323 std.exception: Fix a -dip1000 compilable issue
  dip1000.mak
  std/exception.d
Labels: auto-merge

#6320 Add public examples to std.file + enable DScanner check
  .dscanner.ini
  std/file.d
Labels: auto-merge, documentation

#6326 Fix std.file unittests for auto-tester
  std/file.d
Labels: auto-merge

#6322 std.range: Add example for withPartial for slide + improve docs
  std/range/package.d
Labels: Bug Fix, documentation

#6267 Partially Fix Issue 18596: use arc4random when available for unpredictableSeed
  std/random.d
Labels: Enhancement, auto-merge

#6327 Improved docs and added examples for std.traits.EnumMembers
  std/traits.d
Labels: auto-merge, documentation

#5746 Fix Issue 17862 - std.random.XorshiftEngine.min is wrong when bits == 32
  std/random.d
Labels: Bug Fix, auto-merge, needs review

#6325 Added examples and improved docs of std.traits.extractParameterStorag…
  std/traits.d
Labels: auto-merge, documentation

#6331 Revert fix for 18631.
  std/random.d
Labels: Bug Fix, auto-merge

#6324 Added examples, improved docs, and changed style of std.traits.QualifierOf
  std/traits.d
Labels: auto-merge, documentation

#6333 Added examples for rvalueOf, lvalueOf, isSomeFunction, and Interfaces…
  std/traits.d
Labels: Trivial, auto-merge, documentation

#6329 Fix Issue 18648 - Document the type of std.stdio.stdin and friends
  std/experimental/all.d
  std/stdio.d
Labels: Enhancement, auto-merge, documentation

#6337 Upgrade to DScanner v0.5
  .dscanner.ini
  posix.mak
  std/algorithm/searching.d
  std/concurrency.d
  std/conv.d
  std/digest/crc.d
  std/experimental/allocator/common.d
  std/numeric.d
  std/range/package.d
  std/regex/internal/backtracking.d
  std/traits.d
  std/typecons.d
Labels: auto-merge, automation

#6343 std.bitmanip: Remove outdated debug info + redundant static
  std/bitmanip.d
Labels: Trivial, auto-merge

#5823 std.math: Use DOUBLEPAIR_MSB/LSB for accessing high/low parts of ibmExtended format
  std/math.d
Labels: auto-merge, math

#6342 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/algorithm/searching.d
  std/algorithm/sorting.d
  std/exception.d
  std/experimental/all.d
  std/range/package.d
  std/stdio.d
  std/traits.d
Labels: auto-merge, stable -> master

#6347 Fix spurious build failures in std.file by using more unique test directories
  std/file.d
Labels: auto-merge, automation

#6350 [trivial] Fixed >120 character line in std.datetime.timezone
  .dscanner.ini
  std/datetime/timezone.d
Labels: Trivial, auto-merge, automation

#6334 Modernize std.demangle
  .dscanner.ini
  std/demangle.d
  unittest.d
Labels: Enhancement, auto-merge, documentation

#6335 Suggest using cache before tee.
  std/algorithm/iteration.d
Labels: Trivial, auto-merge, documentation

#6351 [Trivial]std.functional: -dip1000 compilable by @safe => @system unit…
  dip1000.mak
  std/functional.d
Labels: Vision

#6295 std.container.slist: Fix a @safe cannot call @system issue
  dip1000.mak
  std/container/slist.d
Labels: Vision, auto-merge

#6182 Implement apply for Nullable, in analogy to Haskell's monad operation
  changelog/std-typecons-nullable-apply.dd
  std/typecons.d
Labels: Enhancement, auto-merge

#6306 Fixed AscendingPageAllocator race condition
  std/experimental/allocator/building_blocks/ascending_page_allocator.d
Labels: auto-merge, needs review

#6349 [Trivial] Skip Unittests on mismatched_args_check, remove std.range.p…
  .dscanner.ini
  std/range/primitives.d
Labels: Trivial, auto-merge, automation

#6340 std.regex.internal.tests: Fix a -dip1000 compilable issue
  dip1000.mak
  std/regex/internal/tests.d
Labels: Vision, auto-merge

#6254 Work On Issue 18184 - std.zip should be usable in @safe
  std/zip.d
Labels: Vision, attributes, auto-merge

#6354 Improved docs for ImplicitConversionTargets and isAbstractFunction
  std/traits.d
Labels: auto-merge, documentation

#6348 Fix Issue 18663 - std.random.isSeedable has false positives
  std/random.d
Labels: Bug Fix, auto-merge

#6318 Add public examples to std.typecons + DScanner check
  .dscanner.ini
  std/typecons.d
Labels: auto-merge, documentation

#6246 std.algorithm.searching: Fix a -dip1000 compilable issue
  std/algorithm/searching.d
Labels: Enhancement, Vision, auto-merge

#6358 std.datetime: make -dip1000 compatible
  dip1000.mak
  std/datetime/date.d
  std/datetime/systime.d
Labels: Vision, auto-merge

#5820 std.math: Implement more optimal floorImpl for ieeeSingle
  std/math.d
Labels: auto-merge, math

#6355 Fix Issue 18669 - isNestedFunction does not check if parameter is a f…
  std/traits.d
Labels: Bug Fix, auto-merge

#6225 Fix awfully slow sicmp
  std/uni.d
Labels: auto-merge, optimization

#6357 make buildNormalizedPath() @safe
  std/path.d
Labels: Vision, auto-merge

#6363 dip1000.mak: Lift std.conv
  dip1000.mak
Labels: auto-merge

#6365 Skip unittests when dscanner is checking for toHash
  .dscanner.ini
Labels: Trivial, auto-merge

#6344 Make more unittests in std.bitarray public
  std/bitmanip.d
Labels: auto-merge, documentation

#6194 Update how AffixAllocator infers shared from parent
  std/experimental/allocator/building_blocks/affix_allocator.d
Labels: auto-merge

#6364 Add examples for the rest of std.traits and enable the dscanner check
  .dscanner.ini
  std/traits.d
Labels: auto-merge, documentation

#6371 Add public examples to many examples to std.math
  std/math.d
Labels: auto-merge, documentation

#6368 Accomodate Enum init deprecation
  std/stdio.d
  std/traits.d
Labels: auto-merge

#6372 Use MIPS32 instead of MIPS
  std/math.d
Labels: auto-merge

#6383 [Trivial] Delete test in free_tree
  std/experimental/allocator/building_blocks/free_tree.d
Labels: Trivial, auto-merge

#6179 Fix issue 18438 - Handle T* in hasStaticMember like hasMember
  std/traits.d
Labels: Enhancement, auto-merge

#6307 Fix Issue 18638 - The main override of std.range.zip could infer @nogc and nothrow
  std/range/package.d
Labels: Enhancement, auto-merge

#6338 std.typecons: Fix a -dip1000 compilable issue
  dip1000.mak
  std/typecons.d
Labels: Vision, auto-merge

#6374 Add public examples to std.bitmanip + enable DScanner check
  .dscanner.ini
  std/bitmanip.d
Labels: auto-merge

#6377 std.algorithm.iteration: Fix a -dip1000 compilable issue
  dip1000.mak
  std/algorithm/iteration.d
Labels: Vision, auto-merge

#6367 Fix 18689 - std.format should throw FormatException on bad format spec
  .dscanner.ini
  std/format.d
Labels: Bug Fix, auto-merge

#6361 Add ASCII fast path to sicmp & icmp
  std/uni.d
Labels: auto-merge, optimization

#6380 Add public examples to many functions to std.math
  std/math.d
Labels: auto-merge, documentation

#6024 Fix Issue 18223: use memset in uninitializedFillDefault(T[])
  std/experimental/allocator/common.d
  std/experimental/allocator/package.d
Labels: Enhancement, auto-merge

#6394 std.random: add a module-level booktable
  std/random.d
Labels: auto-merge, documentation

#6390 Followup to addition of apply
  std/typecons.d
Labels: auto-merge
