Repository dlang/phobos, pull requests merged in 2018-04, with the labels that each got.

#6399 Add example to chain explaining char corner cases
  std/range/package.d
Labels: documentation

#6191 SList implementation improvements
  std/container/slist.d
Labels: 72h no objection -> merge

#6259 Mark IeeeFlags and FloatingPointControl as @trusted nothrow @nogc
  std/math.d
Labels: math, needs review

#6375 posix.mak: Don't rebuild Phobos when running dscanner
  posix.mak
Labels: auto-merge, automation

#6384 Make std.socket DIP1000 compatible
  dip1000.mak
  std/socket.d
Labels: Vision, auto-merge

#6366 Fix localtime
  std/datetime/timezone.d
Labels: Enhancement, auto-merge

#6378 Fix Issue 18452 - std.zip has size limit of 2 GB
  std/zip.d
Labels: Bug Fix, Enhancement, auto-merge

#6412 Update Phobos's DScanner to 0.5.0
  .dscanner.ini
  posix.mak
Labels: automation

#6415 Make Mallocator use pureMalloc, pureFree and pureRealloc
  std/experimental/allocator/mallocator.d
Labels: Enhancement, auto-merge

#6409 Add public examples to many functions to std.math
  std/math.d
Labels: auto-merge, documentation

#6336 std.math: Remove special cases that attempt to raise FE overflow/underflow flag
  std/math.d
Labels: auto-merge, math

#6405 Make mmap_allocator allocate @safe
  std/experimental/allocator/mmap_allocator.d
Labels: auto-merge

#6393 Add public examples to std.random + enable DScanner check
  .dscanner.ini
  std/random.d
  std/traits.d
Labels: WIP, auto-merge, documentation

#6386 Fix Issue 14637 - Array operations should work on tuples
  std/typecons.d
Labels: Enhancement, auto-merge

#6418 Added examples to std.datetime.systime
  .dscanner.ini
  std/datetime/systime.d
Labels: auto-merge, documentation

#6419 [trivial] Fix EndianSwapper to work with qualified types
  std/bitmanip.d
Labels: Trivial, auto-merge

#6414 Issue 18715 - Non-documented unittests should not use unpredictableSeed or default Random alias
  std/algorithm/internal.d
  std/algorithm/iteration.d
  std/algorithm/mutation.d
  std/algorithm/sorting.d
  std/random.d
Labels: auto-merge

#6356 Simplified std.datetime.package overview
  std/datetime/package.d
Labels: auto-merge, documentation

#6398 Fix Issue 13880 - nothrow @nogc std.algorithm.reduce on fixed-size arrays
  std/algorithm/iteration.d
Labels: Enhancement, auto-merge

#6157 Fix Issue 17982 - Support for const(Class) in algorithm.searching.extremum
  std/algorithm/searching.d
Labels: 72h no objection -> merge, Bug Fix, auto-merge

#6404 Fix Issue 18704 - std/datetime/stopwatch.d(452) assertion failure on auto-tester
  std/datetime/stopwatch.d
Labels: Bug Fix, auto-merge

#6407 Make bitmapped_block allocate @safe
  std/experimental/allocator/building_blocks/bitmapped_block.d
Labels: auto-merge

#6400 Qualify Region, SharedRegion and SbrkRegion allocators
  std/experimental/allocator/building_blocks/region.d
Labels: auto-merge

#6423 Added params and returns to std.array functions
  std/array.d
Labels: auto-merge, documentation

#5822 std.math: Implement floor for ibmExtended reals.
  std/math.d
Labels: 72h no objection -> merge, auto-merge, math

#6425 zlib: remove switch from in front of super()
  std/zlib.d
Labels: Blocking Other Work, Easy Review, auto-merge

#6379 Fix issue 18691 - memory errors in std.regex.Captures
  std/regex/internal/ir.d
  std/regex/internal/tests2.d
  std/regex/package.d
Labels: Bug Fix, auto-merge, stable-priority

#6382 Fix Issue 15768 - std.stdio.trustedStdout accesses __gshared data wit…
  std/stdio.d
Labels: Bug Fix, auto-merge

#6420 Add public examples to all functions in std.math
  std/math.d
Labels: auto-merge, documentation

#6428 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/algorithm/iteration.d
  std/bitmanip.d
  std/regex/internal/ir.d
  std/regex/internal/tests2.d
  std/regex/package.d
Labels: Bug Fix, auto-merge

#6431 Remove outdated status from std.math
  std/math.d
Labels: Trivial, auto-merge, documentation

#6433 Added Params and Returns sections to all functions in std.file
  .dscanner.ini
  std/file.d
Labels: auto-merge, documentation

#6434 Add timeStatusChanged documentation comment
  std/file.d
Labels: auto-merge

#6432 Make GCAllocator usable in pure functions
  std/experimental/allocator/gc_allocator.d
  std/experimental/allocator/typed.d
Labels: auto-merge

#6439 Remove superfluous _range used to avoid auto-highlighting
  std/algorithm/iteration.d
  std/algorithm/mutation.d
  std/algorithm/searching.d
  std/algorithm/setops.d
  std/array.d
  std/format.d
  std/range/interfaces.d
  std/range/package.d
  std/range/primitives.d
  std/uni.d
Labels: Trivial, auto-merge

#6429 Work On Issue 18693 - Remove rndtonl from std.math
  .dscanner.ini
  changelog/rndtonl-deprecated.dd
  std/math.d
Labels: @andralex, auto-merge, math

#6447 Removed scope wide @trusted use in std.typecons
  .dscanner.ini
  std/typecons.d
Labels: Trivial, auto-merge

#6446 Removed scope wide @trusted use in std.math
  .dscanner.ini
  std/math.d
Labels: Trivial, auto-merge

#6448 [Trivial] Fix double initialization of field errno in std/file.d
  std/file.d
Labels: Trivial, auto-merge

#6450 Remove version(unittest) imports to avoid extra imports in user code.
  std/algorithm/sorting.d
  std/array.d
  std/ascii.d
  std/bitmanip.d
Labels: Easy Review, auto-merge

#6451 Remove version(unittest) imports to avoid extra imports in user code.
  std/concurrency.d
  std/conv.d
  std/digest/crc.d
  std/digest/hmac.d
  std/digest/sha.d
  std/encoding.d
Labels: Easy Review, auto-merge

#6445 Added public examples to std.string
  .dscanner.ini
  std/string.d
Labels: auto-merge, documentation

#6453 More removal of version(unittest)
  std/digest/murmurhash.d
  std/internal/cstring.d
  std/math.d
  std/net/isemail.d
  std/numeric.d
  std/parallelism.d
  std/path.d
  std/range/primitives.d
  std/socket.d
  std/traits.d
Labels: Easy Review

#6435 Make references to input ranges a link to isInputRange
  std/algorithm/iteration.d
  std/algorithm/setops.d
  std/container/array.d
  std/container/dlist.d
  std/container/slist.d
  std/csv.d
  std/file.d
  std/format.d
  std/meta.d
  std/parallelism.d
  std/path.d
  std/random.d
  std/range/package.d
  std/range/primitives.d
  std/stdio.d
  std/uni.d
  std/utf.d
Labels: auto-merge, documentation, needs review

#6411 make/makeArray: take advantage of allocators with smth. faster than allocate+memset zero
  std/experimental/allocator/common.d
  std/experimental/allocator/gc_allocator.d
  std/experimental/allocator/mallocator.d
  std/experimental/allocator/mmap_allocator.d
  std/experimental/allocator/package.d
Labels: auto-merge, optimization

#6442 Added Params and Returns to std.algorithm.iteration
  .dscanner.ini
  std/algorithm/iteration.d
Labels: auto-merge, documentation

#6455 Add alignedAllocate for StatsCollector
  std/experimental/allocator/building_blocks/stats_collector.d
Labels: Enhancement, allocators, auto-merge

#6408 Add multiblock support for shared and non-shared BitmappedBlock
  changelog/shared-bitmapped-block.dd
  std/experimental/allocator/building_blocks/bitmapped_block.d
Labels: 72h no objection -> merge

#6456 Add alignedAllocate for AllocatorList
  std/experimental/allocator/building_blocks/allocator_list.d
Labels: Enhancement, allocators, auto-merge

#6392 Allow to add additional DFLAGS when building Phobos
  posix.mak
Labels: auto-merge, automation

#6449 Fix Issue 18760 - theAllocator dangling reference bug
  std/experimental/allocator/package.d
Labels: Bug Fix, allocators

#5873 Issue 17127 - bad example code for std.concurrency.Generator
  std/concurrency.d
Labels: auto-merge

#6460 Add deallocateAll for SharedRegion
  std/experimental/allocator/building_blocks/region.d
Labels: Enhancement, allocators, auto-merge

#6328 Fix Issue 18525: std.algorithm.mutate.remove should work on mutable strings
  std/algorithm/mutation.d
Labels: Bug Fix, auto-merge

#6470 [Trivial] Annotates std.random unittests with `@nogc` when already possible
  std/random.d
Labels: Trivial

#6468 [trivial] Fix `Nullable.get` docs
  std/typecons.d
Labels: Trivial, auto-merge, documentation

#6472 fix issue 17084 - Can't sort array of structs with alias this
  std/exception.d
Labels: Bug Fix, Enhancement

#6463 Make AffixAllocator parent pure
  std/experimental/allocator/building_blocks/affix_allocator.d
Labels: Enhancement, allocators, auto-merge

#6413 Fix Issue 17806 - processAllocator getter will override set value if …
  std/experimental/allocator/package.d
Labels: Bug Fix, allocators, auto-merge

#6476 [Trivial] zip & zlib: don't zero-fill buffers before writing to them
  std/zip.d
  std/zlib.d
Labels: Trivial, auto-merge

#6454 Added Params and Returns to std.functional
  .dscanner.ini
  std/functional.d
Labels: auto-merge, documentation

#6466 Added examples to std.path
  .dscanner.ini
  std/path.d
Labels: auto-merge, documentation

#6481 Fix std.variant unittest
  std/variant.d
Labels: auto-merge

#6480 Fix std.conv.emplaceRef() for 0-sized types
  std/conv.d
Labels: auto-merge

#6482 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/conv.d
  std/math.d
  std/variant.d
Labels: auto-merge

#6474 fix conversion from wchar to char in LockingTextWriter.put
  std/stdio.d
Labels: auto-merge

#6486 fix Issue 18800 - Array.length setter segfaults for payloads with indirections
  std/container/array.d
Labels: Bug Fix

#6484 Fix stdio File.open / resetFile / detach / refcount
  std/stdio.d
Labels: Bug Fix, auto-merge

#6487 [Trivial] truncl is pure in core/stdc/math -> remove specialization
  std/math.d
Labels: Bug Fix, Trivial
