Repository dlang/phobos, pull requests merged in 2018-09, with the labels that each got.

#6685 Fix issue 18142 - checkint opOpAssign doesn't accept checkedints
  std/experimental/checkedint.d
Labels: Enhancement, auto-merge

#6670 Fix Issue 19085 - std.experimental.allocator.makeArray should work with void
  std/experimental/allocator/common.d
  std/experimental/allocator/package.d
Labels: Bug Fix, auto-merge

#6684 Fix issue 19200 - Variant operators don't overload correctly
  std/variant.d
Labels: Bug Fix, auto-merge

#6687 fix substitute for single subrange subst
  std/algorithm/iteration.d
Labels: Bug Fix, auto-merge

#6689 switch Digital Mars copyright to D Language Foundation
  std/bitmanip.d
  std/compiler.d
  std/conv.d
  std/demangle.d
  std/file.d
  std/format.d
  std/math.d
  std/meta.d
  std/mmfile.d
  std/outbuffer.d
  std/process.d
  std/signals.d
  std/stdint.d
  std/stdio.d
  std/string.d
  std/system.d
  std/traits.d
  std/typetuple.d
  std/uri.d
  std/utf.d
  std/windows/charset.d
  std/windows/syserror.d
  std/zip.d
  std/zlib.d
Labels: Easy Review, auto-merge

#6694 Fix issue 19228 - hasAliasing fails on static arrays
  std/traits.d
Labels: Bug Fix, auto-merge

#6517 Fix Issue 18683 - no toHash in rbtree
  std/container/rbtree.d
Labels: Bug Fix, auto-merge

#6467 Fix Issue 18675 - Missing toHash in std/experimental/checkedint.d
  changelog/std-experimental-checkedint-toHash.dd
  std/experimental/checkedint.d
Labels: Bug Fix, auto-merge

#6696 [ARM] [GDC] Make hasExceptionTraps pure on ARM
  std/math.d
Labels: auto-merge

#6698 Fix Issue 19236 - Replace runtime `typeid(T).initializer().ptr is null` checks with compile-time `__traits(isZeroInit, T)`
  std/algorithm/mutation.d
  std/typecons.d
Labels: Enhancement, auto-merge, betterC

#6677 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/math_float_double_implementations.dd
  changelog/std-algorithm-iteration-joiner.dd
  changelog/std-algorithm-searching-skipOver.dd
  changelog/std-array-asStatic.dd
  changelog/std-datetime-timezone-remove.dd
  posix.mak
  std/typecons.d
Labels: Bug Fix, auto-merge

#6697 Replace isInitAllZeroBits with new __traits(isZeroInit)
  std/experimental/allocator/common.d
  std/experimental/allocator/package.d
Labels: auto-merge, refactoring

#6705 Fix buildkite build
  posix.mak
Labels: auto-merge

#6706 Ddoc: fix unescaped dollar sign
  std/regex/package.d
Labels: auto-merge

#6713 Fix issue 19252: avoid ludicrous format length overestimate
  std/format.d
Labels: Bug Fix

#6709 Fix line endings in .editorconfig
  .editorconfig
Labels: auto-merge

#6708 std.math: Remove support for IBM extended reals
  std/math.d
Labels: auto-merge, math

#6712 Fix issue 19240 - std.typecons.Tuple should check for reserved identi…
  std/typecons.d
Labels: Bug Fix, auto-merge

#6710 Fix Issue 18851 -- std.net.curl.post cannot be used with !ubyte
  std/net/curl.d
Labels: Bug Fix, auto-merge

#6692 Implement allocateZeroed for building-block allocators
  std/experimental/allocator/building_blocks/affix_allocator.d
  std/experimental/allocator/building_blocks/allocator_list.d
  std/experimental/allocator/building_blocks/bucketizer.d
  std/experimental/allocator/building_blocks/fallback_allocator.d
  std/experimental/allocator/building_blocks/free_list.d
  std/experimental/allocator/building_blocks/quantizer.d
  std/experimental/allocator/building_blocks/scoped_allocator.d
  std/experimental/allocator/building_blocks/segregator.d
  std/experimental/allocator/building_blocks/stats_collector.d
  std/experimental/allocator/gc_allocator.d
  std/experimental/allocator/mallocator.d
Labels: auto-merge

#6714 Remove separate @betterC tests
  posix.mak
  test/betterC/algorithm.d
Labels: auto-merge, betterC

#6715 Fix formattedRead throwing Exception
  std/format.d
Labels: auto-merge

#6721 Fix typo
  std/conv.d
Labels: Trivial, auto-merge, documentation
