Repository dlang/phobos, pull requests merged in 2018-07, with the labels that each got.

#6623 Cherry-pick #6616 (DScanner bump) to stable
  posix.mak
  std/experimental/typecons.d
  std/traits.d
  std/typecons.d
Labels: Blocking Other Work, Bug Fix

#6627 [Ddoc] make "grapheme" a link
  std/uni.d
Labels: auto-merge

#6624 Wrong filetype with a changelog entry
  changelog/std-array-asStatic.dd
Labels: documentation

#6628 [trivial] Fix AA tests: order of AA elements isn't determined
  std/net/curl.d
  std/uri.d
Labels: Trivial

#6617 Fix issue 16639 - Review std.json wrt this article on JSON edge cases and ambiguities
  std/json.d
Labels: Enhancement, auto-merge

#5755 Make statTimeToStdTime public
  std/file.d
Labels: 72h no objection -> merge, auto-merge

#6497 Fix issue 15732 - std.function partial does not work with function / delegate references
  std/functional.d
Labels: Bug Fix, auto-merge

#6635 Issue 19055 - [404 Not Found] std.digest.digest
  index.d
Labels: auto-merge

#6637 fix issue 19094 - Anchored section does not exist in std.uni.normaliz…
  std/uni.d
Labels: Bug Fix

#6594 Fix issue 19003: don't call toString on T.init
  std/format.d
Labels: 72h no objection -> merge, auto-merge

#6639 [Trivial] std.typecons: Get rid of unnecessary core.stdc.stdint.uintptr_t import
  std/typecons.d
Labels: Trivial, auto-merge

#6638 Revert @trusted hotfix for std.uni
  std/uni.d
Labels: Blocking Other Work, auto-merge

#6634 Fix Issue 19041 - errnoEnforce: example does not compile
  std/exception.d
Labels: Enhancement, auto-merge

#6619 Fix issue 19037: use move/moveEmplace in Nullable
  std/typecons.d
Labels: Enhancement, auto-merge
