Repository dlang/phobos, pull requests merged in 2018-08, with the labels that each got.

#6650 Update D-Scanner to support the new enum member attributes
  posix.mak
Labels: auto-merge

#6651 Move some deprecations along.
  std/conv.d
  std/string.d
Labels: auto-merge

#6527 Adds const to Typedef.toString
  std/typecons.d
Labels: 72h no objection -> merge, auto-merge

#6636 Fix Issue 19082 - Cannot inline "...Slides.numberOfFullFrames", "...Slides.gap"
  std/range/package.d
Labels: Bug Fix, Enhancement, auto-merge

#6633 Extend std.conv.parse for strings to full ieeeQuadruple precision and other fixes
  std/conv.d
Labels: auto-merge

#6654 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/range/package.d
Labels: Bug Fix

#6655 [stable] Remove superfluous core.stdc.* dependencies in std.{conv,random}
  std/conv.d
  std/random.d
Labels: auto-merge

#6656 Fix Issue 19147 - Reduce template bloat in std.complex by using const arguments
  std/complex.d
Labels: Bug Fix, auto-merge

#6658 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/conv.d
  std/random.d
Labels: auto-merge

#6653 Fix Issue 19138 - std.uuid.randomUUID should not depend on std.random.Random being Mt19937
  std/uuid.d
Labels: Bug Fix

#6662 Don't run DScanner in GDB anymore
  posix.mak
Labels: Blocking Other Work, auto-merge

#6661 Remove duplicate definitions of DOUBLEPAIR_MSB & DOUBLEPAIR_LSB for IBM doubledouble
  std/math.d
Labels: auto-merge

#6657 Fix Issue 14001 & Issue 19156 - `@nogc` std.random.randomCover and std.random.randomShuffle
  std/random.d
Labels: Enhancement, auto-merge

#6649 Fix Issue 19135: Rename std.json.JSON_TYPE to JsonType with lowercase attributes
  std/json.d
Labels: Enhancement, auto-merge

#6143 Fix Issue 12335 - std.algorithm.skipOver should support multiple args like startsWith
  changelog/std-algorithm-searching-skipOver.dd
  std/algorithm/searching.d
Labels: 72h no objection -> merge, Enhancement, auto-merge

#6272 Implement std.math.{atan[2],tan,exp[2],expm1} for single- and double-precision
  changelog/math_float_double_implementations.dd
  std/math.d
Labels: auto-merge

#6668 Add a changelog entry for each's early stopping
  changelog/std-algorithm-iteration-each-early-stopping.dd
Labels: Easy Review, auto-merge, documentation

#6672 [stable] std.exception: Make unittest less brittle
  std/exception.d
Labels: auto-merge

#6667 Fix dxml regression in multiple arguments skipOver
  std/algorithm/searching.d
Labels: Bug Fix, Easy Review, auto-merge

#6664 Fix issue 19162 - [REG: 2.079.0] Public Import Overlapping Names Conflict Resolution
  std/math.d
Labels: Bug Fix, auto-merge

#6675 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/algorithm/searching.d
  std/exception.d
  std/math.d
Labels: Enhancement, auto-merge, stable -> master

#6645 Allow @betterC tests in Phobos
  .circleci/run.sh
  posix.mak
  std/algorithm/comparison.d
  std/internal/attributes.d
Labels: auto-merge, betterC

#6680 fix issue 11431 - std.file.slurp fails with Windows newlines
  std/file.d
Labels: Bug Fix, auto-merge

#6681 Fix issue 11959 - Set private symbols declared in version(unittest) blocks
  std/conv.d
  std/datetime/date.d
  std/datetime/systime.d
  std/experimental/allocator/building_blocks/ascending_page_allocator.d
  std/format.d
  std/internal/math/biguintcore.d
  std/parallelism.d
  std/path.d
  std/process.d
  std/stdio.d
  std/traits.d
  std/utf.d
Labels: Bug Fix, auto-merge

#6674 [stable] Fix Issue 18682: Forward Nullable.toHash to contained value, if non-null.
  std/typecons.d
Labels: Bug Fix, auto-merge

#6683 Remove inout from JSON valuetype getters
  std/json.d
Labels: auto-merge

#6682 Add a getter and setter for booleans in JSON
  std/json.d
Labels: Enhancement, auto-merge
