Repository dlang/phobos, pull requests merged in 2018-12, with the labels that each got.

#6788 [dmd-cxx] Disable auto-tester-test from running
  posix.mak
  win32.mak
  win64.mak
Labels: Trivial

#6791 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/numeric.d
  std/traits.d
Labels: Bug Fix, auto-merge

#6793 Fix issue 19466 - functionLinkage documentation omits some values
  std/traits.d
Labels: auto-merge

#6797 SHA on Win64: use SSSE3 version by adjusting register usage
  std/digest/sha.d
  std/internal/digest/sha_SSSE3.d
Labels: auto-merge

#6789 Fix issue 19456 - ParameterIdentifierTuple incorrect for abstract met…
  std/traits.d
Labels: Bug Fix, auto-merge

#6798 min/max shouldn't pull std.format.
  std/algorithm/comparison.d
Labels: auto-merge

#6796 canFind: added example to search for multiple needles in a hay stack.
  std/algorithm/searching.d
Labels: auto-merge, documentation

#6807 [trivial] Fix `dirEntries` docs
  std/file.d
Labels: Trivial, auto-merge

#6808 Fix Issue 18755 - std.typecons.Rebindable breaks @safe-ty
  std/typecons.d
Labels: Bug Fix, auto-merge

#6805 Fix Issue 19133 - core.exception.rangeerror@std/file.d(3812)
  std/file.d
Labels: Bug Fix

#6800 Simplify isInnerClass
  std/traits.d
Labels: 72h no objection -> merge, auto-merge

#6809 Replace imports of core.sys.windows.windows to speed up compilation
  std/datetime/systime.d
  std/datetime/timezone.d
  std/experimental/allocator/building_blocks/ascending_page_allocator.d
  std/experimental/allocator/mmap_allocator.d
  std/file.d
  std/format.d
  std/internal/cstring.d
  std/internal/windows/advapi32.d
  std/mmfile.d
  std/net/curl.d
  std/parallelism.d
  std/process.d
  std/socket.d
  std/stdio.d
  std/windows/charset.d
  std/windows/registry.d
  std/windows/syserror.d
Labels: auto-merge

#6813 logger: print log level string.
  std/experimental/logger/filelogger.d
Labels: auto-merge

#6814 do not mix arrays and raw GC.realloc/free: base address of arrays are…
  std/file.d
Labels: auto-merge

#6810 Fix Issue 18913 - Cannot move static array of non-copyable type
  std/algorithm/mutation.d
Labels: Bug Fix, auto-merge

#6815 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/array.d
  std/complex.d
  std/file.d
  std/math.d
  std/traits.d
  std/typecons.d
  std/variant.d
Labels: Bug Fix

#6816 [trivial] unittest: set pagesize by using sysconf(_SC_PAGESIZE) on po…
  std/mmfile.d
Labels: Trivial, auto-merge

#6817 staticArray needs to appear in jump table.
  std/array.d
Labels: Trivial, auto-merge, documentation

#6819 Merge remote-tracking branch 'upstream/stable' into merge_stable
  posix.mak
  std/net/curl.d
Labels: auto-merge

#6799 simplify maxAlignment
  std/traits.d
Labels: auto-merge

#6820 Fix Issue 19526 - make RefCounted work in betterC
  std/typecons.d
Labels: Enhancement, auto-merge, betterC

#6803 Fix Issue 19213 - goto skips declaration of variable in std.algorithm…
  std/algorithm/iteration.d
Labels: Bug Fix

#5952 Make std.typecons.Tuple betterC compatible
  std/typecons.d
Labels: Bug Fix, Enhancement, auto-merge, betterC
