Repository dlang/phobos, pull requests merged in 2019-01, with the labels that each got.

#6821 update D-Scanner
  posix.mak
Labels: auto-merge

#6823 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/pr6580.dd
  std/algorithm/iteration.d
Labels: Bug Fix, auto-merge

#6824 fix Issue 18519: missing curl + phobos = std.net.curl unittest timing out
  posix.mak
  std/net/curl.d
Labels: Bug Fix, auto-merge

#6826 Remove no longer available issue stats and add a Buildkite badge
  README.md
Labels: auto-merge

#6209 Use enums for hasToString
  std/format.d
Labels: 72h no objection -> merge

#6829 [dmd-cxx] Fix windows builds and backport makefile changes
  std/stdio.d
  win32.mak
  win64.mak
Labels: Easy Review

#6830 std.random: make dip1000 compliant
  std/random.d
Labels: Blocking Other Work, auto-merge

#6832 Fix issue 19572: Prevent Appender from implicitly calling struct constructors to cast away const.
  std/array.d
Labels: Bug Fix, auto-merge

#6833 [non-DMD] std.random seed bootstrap: don't count on reading an uninitialized variable being treated as an ordinary read
  std/random.d
Labels: Bug Fix, auto-merge

#6836 Add minimum HPPA support to phobos
  std/experimental/allocator/building_blocks/region.d
  std/math.d
Labels: Easy Review, auto-merge

#6835 std.uni: add scope to addInterval()
  std/uni.d
Labels: Blocking Other Work, Vision

#6837 [dmd-cxx] Backport AA unittest fixes
  std/net/curl.d
  std/uri.d
Labels: Easy Review, auto-merge

#6838 [dmd-cxx] Backport std.math fixes and a few other port bugs.
  posix.mak
  std/datetime/systime.d
  std/experimental/allocator/building_blocks/region.d
  std/experimental/typecons.d
  std/math.d
  std/net/curl.d
Labels: Bug Fix, Easy Review

#6839 alias std.array.Appender.opOpAssign to put
  std/array.d
Labels: auto-merge

#6840 alias CustomFloat.opCast to get
  std/numeric.d
Labels: auto-merge

#6841 Fix Issue 19532 - chunkBy errors involving non-forward input ranges
  std/algorithm/iteration.d
Labels: Bug Fix, auto-merge

#6849 [Trivial] Fix typo in SetDifference docs.
  std/algorithm/setops.d
Labels: Trivial, auto-merge
