Repository dlang/phobos, pull requests merged in 2019-10, with the labels that each got.

#7197 Reference std.format.formatValue from std.conv
  std/conv.d
Labels: auto-merge

#7205 Fix Issue 15230 - Inconsistent std.range.SortedRange predicate checks
  std/algorithm/sorting.d
  std/range/package.d
Labels: Bug Fix, auto-merge

#7209 std.numeric: Add some unittests to improve coverage.
  std/numeric.d
Labels: auto-merge

#7212 Revert "Fix issue 20205 - std.math: Wrong result for abs(int.min)"
  std/math.d
Labels: Bug Fix, auto-merge

#7201 std.zip: Replace magic constants by constants named after specs
  std/zip.d
Labels: auto-merge

#7194 BitArray fixes
  std/bitmanip.d
Labels: Enhancement, auto-merge

#7213 Add unittest to std.math to avoid falling into the trap again.
  std/math.d
Labels: auto-merge

#7214 Fix issue 20205 - std.math: Wrong result for abs(int.min)
  std/math.d
Labels: Bug Fix, auto-merge

#7198 Fix issue 20239 - chameleon zip-file should be rejected by std.zip
  std/zip.d
Labels: Bug Fix, auto-merge

#7215 Silence warning: struct Rebindable has method toHash, however it cannot be called with const(Rebindable!(const(C))) this.
  std/algorithm/iteration.d
  std/typecons.d
Labels: auto-merge

#7221 Fix issue 20287 - std.zip: Wrong compressed data
  std/zip.d
Labels: Bug Fix, auto-merge

#7223 Fix issue 20027 - std.zip susceptible to zip malware attacks
  std/zip.d
Labels: Bug Fix, auto-merge

#7233 Fix Issue 19283 - [std.mathspecial] documentation for normal distribution doesn't list parameters
  std/mathspecial.d
Labels: Bug Fix

#7220 std.uri: Add unittests for 100% code coverage.
  std/uri.d
Labels: auto-merge-squash

#7229 Fix issue #20295 - std.zip: zip64 with 0xff bytes in end of central dir record do not work
  std/zip.d
Labels: Bug Fix, auto-merge

#7232 Fix issue 19626 - RedBlackTree of an enum fails in unittest mode
  std/container/rbtree.d
Labels: Bug Fix

#7231 Fix issues 20301 and 20302
  std/functional.d
  std/regex/package.d
Labels: Bug Fix, auto-merge

#7236 Fix Issue 20263 - Wrong value for CustomFloat.min_exp
  std/numeric.d
Labels: Bug Fix

#7235 Fix Issue 20283 - CustomFloat.max_exp not working in some cases
  std/numeric.d
Labels: Bug Fix

#7234 Fix Issue 20282 - CustomFloat.dig fails at some values.
  std/numeric.d
Labels: Bug Fix

#7239 Update header of sqlite3 to 3.30.1
  etc/c/sqlite3.d
Labels: auto-merge

#7219 Fix issues 20260, 20281, 20284 - Limitations of CustomFloat.
  std/numeric.d
Labels: Bug Fix

#7240 Fix Issue 10448 - min and max are not NaN aware
  std/algorithm/comparison.d
  std/algorithm/searching.d
Labels: Bug Fix

#7222 Fix Issue 20288 - std.format with separator and double causes RangeError
  std/conv.d
  std/format.d
Labels: Bug Fix, Enhancement, auto-merge

#7245 Replace `in` with `const` in preparation of dmd change
  std/experimental/logger/filelogger.d
  std/json.d
  std/net/curl.d
Labels: auto-merge

#7246 Merge stable
  std/functional.d
  std/regex/package.d
  std/zip.d
Labels: Bug Fix, stable -> master

#7248 Added forgotten assert keyword
  std/utf.d
Labels: auto-merge

#7238 Fix Issue 20261 - CustomFloat.epsilon yields infinity
  std/numeric.d
Labels: Bug Fix

#7254 Fix Issue 9592 - Justified Tuple printing
  std/format.d
Labels: Bug Fix, auto-merge

#7228 std/math.d: Explicitly handle zero and inf in scalbn.
  std/math.d
Labels: auto-merge, math

#7257 Fix issue 20328: only check isInputRange when we've already excluded toString overload.
  std/format.d
Labels: Bug Fix, Enhancement

#7262 Add `scope` preparing for `in` to become `const scope`
  std/digest/package.d
  std/string.d
Labels: auto-merge

#7260 Error if circleci script is run with no arguments
  .circleci/run.sh
Labels: auto-merge

#7250 handle timeout on Windows the same as on Linux - no other way in curr…
  std/socket.d
Labels: Bug Fix, auto-merge
