Repository dlang/phobos, pull requests merged in 2019-02, with the labels that each got.

#6850 [dox] Cross-reference .merge and .multiwayMerge.
  std/algorithm/setops.d
  std/algorithm/sorting.d
Labels: auto-merge

#6847 Use moved core.lifetime.forward for std.functional.forward
  std/functional.d
Labels: auto-merge

#6846 std.traits: use assumePurein the public example
  std/traits.d
Labels: auto-merge

#6853 Fix issues 19644, 19647 - std.range.takeOne.opSlice bugs
  std/range/package.d
Labels: Bug Fix, auto-merge-squash

#6859 [dmd-cxx] Backport non-math related patches from #5358
  std/experimental/allocator/mallocator.d
  std/file.d
  std/math.d
  std/system.d
Labels: auto-merge

#6861 Fix typo in documentation.
  std/file.d
Labels: auto-merge

#6862 Fix documentation link.
  std/file.d
Labels: Trivial, auto-merge

#6857 [Revival of PR 4136] Fix issue 15853 - std.random save methods must be const
  std/random.d
Labels: Enhancement, auto-merge

#6866 SortedRange.opSlice() should be return scope
  std/range/package.d
Labels: Blocking Other Work

#6865 Fix issues 19042, 19681 - std.range.padRight bugs
  std/range/package.d
Labels: Bug Fix, auto-merge

#6872 Fix issue 19686 - sgn is too greedy
  std/math.d
Labels: Enhancement, auto-merge

#6874 Remove underscore.
  std/container/package.d
Labels: auto-merge

#6871 range.only() returns its parameters
  std/range/package.d
Labels: auto-merge

#6875 toUTF16z cannot be used for LPWSTR.
  std/utf.d
Labels: Bug Fix, auto-merge

#6877 adjust setops.cartesianProduct() for dip1000
  std/algorithm/setops.d
Labels: Vision, auto-merge

#6878 core.stdc.stdlib._Exit not core.stdc.stdlib._exit
  std/process.d
Labels: auto-merge

#6873 Fix issue 19689: don't use recursive template parameter iteration in std.traits.
  std/traits.d
Labels: 72h no objection -> merge, Bug Fix, auto-merge

#6879 Disable OSX-32 on the auto-tester
  posix.mak
Labels: auto-merge
