Repository dlang/phobos, pull requests merged in 2019-03, with the labels that each got.

#6890 Disable the style_lint target on CircleCi
  .circleci/config.yml
  .circleci/run.sh
  dip1000.mak
Labels: auto-merge

#6882 Update D-scanner version
  posix.mak
Labels: auto-merge

#6891 std.range.package.d dip1000
  dip1000.mak
  std/range/package.d
Labels: Vision, auto-merge

#6825 fix quoting in win64.mak: add them only when invoking command
  etc/c/zlib/win64.mak
  win64.mak
Labels: auto-merge

#6893 Remove redundant body of @disable functions. Issue 14854 DMD
  std/container/binaryheap.d
  std/datetime/systime.d
  std/parallelism.d
  std/traits.d
  std/windows/registry.d
Labels: auto-merge-squash

#6888 Fixed comparison bug
  changelog/comparison_bug.dd
  std/algorithm/comparison.d
Labels: auto-merge-squash

#6896 Fix Issue 18728 - std.math.fdim does not handle nan correctly
  std/math.d
Labels: Bug Fix, auto-merge-squash

#6901 byUTF: don't read from range in constructor
  std/utf.d
Labels: auto-merge

#6900 add copy constructor to byUTF()
  std/utf.d
Labels: auto-merge

#6903 byUTF: use copy constructor for save()
  std/utf.d
Labels: @safe / scope / return, auto-merge

#6899 Fix for the issue 18806: InputRange for std.algorithm.minIndex
  std/algorithm/searching.d
Labels: Enhancement, auto-merge

#6904 ChooseResult: use of unions need to be @trusted
  std/range/package.d
Labels: auto-merge

#6906 compile std.path with -dip1000 2nd try
  dip1000.mak
Labels: Vision, auto-merge

#6907 compile std.format with -dip1000
  dip1000.mak
  std/format.d
Labels: Vision, auto-merge

#6909 FormatSpec scope parameters
  std/format.d
Labels: scope

#6910 more scope for FormatSpec
  std/array.d
  std/bigint.d
  std/bitmanip.d
  std/complex.d
Labels: auto-merge, scope

#6911 Even more scope for FormatSpec
  std/container/rbtree.d
  std/numeric.d
  std/typecons.d
  std/uni.d
Labels: auto-merge, scope

#6912 [Trivial] std.file: Optimize deleteme a bit
  std/file.d
Labels: Trivial, auto-merge, optimization

#6908 std.outbuffer: compile with -dip1000
  dip1000.mak
Labels: Vision, auto-merge

#6917 [TRIVIAL] Remove redundant constraint from empty() range primitive
  std/range/primitives.d
Labels: auto-merge

#6918 Improve documentation for StringTypeOf
  std/traits.d
Labels: auto-merge, documentation

#6913 Fix Issue 19751 - std.stdio.File should not retry fclose after error
  std/stdio.d
Labels: Bug Fix, auto-merge

#6915 std.stdio: -dip1000
  dip1000.mak
Labels: Vision, auto-merge

#6919 std.socket: -dip1000
  dip1000.mak
  std/socket.d
Labels: Vision, auto-merge

#6920 std.algorithm.searching: compile with -dip1000
  dip1000.mak
Labels: Vision, auto-merge

#6914 std.file: -dip1000
  dip1000.mak
Labels: Vision, auto-merge

#6926 std.experimental.logger.filelogger: compile with -dip1000
  dip1000.mak
Labels: Vision, auto-merge

#6923 std.net.curl: compile with -dip1000
  dip1000.mak
Labels: Vision, auto-merge

#6925 std.experimental.allocator.package: compile with -dip1000
  dip1000.mak
Labels: Vision

#6916 std.concurrency: -dip1000
  dip1000.mak
Labels: Vision

#6922 std.container.rbtree: compile with -dip1000
  dip1000.mak
  std/container/rbtree.d
Labels: Vision

#6889 Move std.experimental.all to std
  changelog/std-all.dd
  posix.mak
  std/experimental/all.d
  std/package.d
  win32.mak
  win64.mak
Labels: auto-merge

#6930 add std.range.primitives.Autodecoding
  std/range/primitives.d
  std/traits.d
Labels: auto-merge

#6346 make `group`, `chain`, and `choose` compatible with `RefRange`
  std/algorithm/iteration.d
  std/range/package.d
Labels: auto-merge

#6934 fix issue 19765 - std.algorithm.searching.findAmong doesn't `save` li…
  std/algorithm/searching.d
Labels: Bug Fix

#6936 [CircleCi] Fix build by using Ubuntu 18.04 as base
  .circleci/config.yml
  .circleci/run.sh
Labels: Blocking Other Work, auto-merge

#6935 make `cycle`, `splitter`, `roundRobin`, and `until` compatible with `RefRange`
  std/algorithm/iteration.d
  std/algorithm/searching.d
  std/range/package.d
Labels: auto-merge

#6937 Consolidate overloads of copy()
  std/algorithm/mutation.d
Labels: auto-merge

#6938 add workaround for slow compilation of large unittest functions
  std/algorithm/searching.d
  std/datetime/systime.d
  std/random.d
  std/range/package.d
  std/string.d
Labels: auto-merge

#6942 variant.d: Gated unittests behind version(StdDdoc)
  std/variant.d
Labels: Bug Fix, Enhancement
