Repository dlang/phobos, pull requests merged in 2019-08, with the labels that each got.

#7119 Appender and RefAppender: use opSlice() instead of data()
  changelog/array-opslice.dd
  std/array.d
Labels: auto-merge

#7121 Fix issues 19696, 19697, 16132 - ReplaceType bugs
  std/typecons.d
Labels: Bug Fix, Enhancement, auto-merge

#7123 Fix Issue 20098 - Improve result of printing std.regex compiled pattern
  std/regex/internal/ir.d
  std/regex/package.d
Labels: Enhancement, auto-merge

#7112 Fix issue 20064,20069 - format functions make their final width and digits grouping conform to POSIX definition
  std/format.d
Labels: Bug Fix, Enhancement, auto-merge

#7122 Fix issue 20097
  std/concurrency.d
Labels: Bug Fix, auto-merge

#7125 Clarify that buf can be shortened in readln
  std/stdio.d
Labels: auto-merge-squash

#7120 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/algorithm/mutation.d
  std/conv.d
  std/experimental/allocator/package.d
  std/range/package.d
  std/typecons.d
Labels: Enhancement, auto-merge

#7127 Fix copy-paste error in std.functional.pipe doc
  std/functional.d
Labels: auto-merge, documentation

#7129 start making use of isAutodecodableString()
  std/range/primitives.d
Labels: auto-merge, refactoring

#7131 Fix Issue 20129 - AA require with File values gives "Error: `return` …
  std/stdio.d
Labels: Bug Fix, auto-merge

#7128 improve documentation and tests for isAutodecodable()
  std/traits.d
Labels: auto-merge, documentation

#7133 fix array(String) to work with no autodecode
  std/array.d
Labels: auto-merge

#7104 Addes assert messages to bigint
  std/bigint.d
  std/internal/math/biguintcore.d
  std/internal/math/biguintnoasm.d
Labels: auto-merge

#7135 fix unittests for array.join() for no autodecode
  std/array.d
Labels: auto-merge

#7136 adds assert messages to std.concurrency
  std/concurrency.d
Labels: auto-merge

#7141 std.uni: Disambiguate templates with autodecoding off
  std/uni.d
Labels: auto-merge

#7139 std.file: Fix unittest for no autodecode
  std/file.d
Labels: auto-merge

#7140 std.stdio: Fix failing unittest with no autodecode
  std/stdio.d
Labels: auto-merge

#7142 Rewrite dubious refRange() shortcuts in unittests
  std/algorithm/iteration.d
  std/algorithm/searching.d
  std/range/package.d
Labels: auto-merge

#7134 fix assocArray() unittests for no autodecode
  std/array.d
Labels: auto-merge, no autodecode

#7145 UTFException should derive from UnicodeException
  std/utf.d
Labels: auto-merge

#7126 ieeeFlags unittest: the optimizer might remove operations that the te…
  std/math.d
Labels: auto-merge

#7138 std.format: Fix compilation with no autodecode
  std/conv.d
  std/format.d
Labels: no autodecode

#7146 std.utf.byUTF: add option to throw on invalid UTF
  std/utf.d
Labels: auto-merge, no autodecode

#7116 std.process: add missing check for failed malloc()
  std/process.d
Labels: auto-merge-squash

#7150 std.process: use local imports
  std/process.d
Labels: Trivial

#7153 Fix Issue 20159 - Make std.math.scalbn work in CTFE
  std/math.d
Labels: Enhancement, auto-merge

#7155 Issue 20159 Followup - fix ldc-win32 test failure
  std/math.d
Labels: auto-merge

#7156 [stable] Fix std.variant unittest
  std/variant.d
Labels: auto-merge

#7160 Fix CircleCI build
  .circleci/config.yml
  .circleci/run.sh
Labels: auto-merge

#7159 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/variant.d
Labels: auto-merge, stable -> master

#7149 std.net.curl: Fix example in HTTP documentation
  std/net/curl.d
Labels: auto-merge

#7161 Replace `sizediff_t` with `ptrdiff_t` in std.random.d
  std/random.d
Labels: auto-merge

#7162 Replace `hash_t` and `sizediff_t` with `size_t` and `ptrdiff_t`
  std/algorithm/searching.d
  std/range/package.d
  std/typecons.d
Labels: auto-merge
