Repository dlang/phobos, pull requests merged in 2019-12, with the labels that each got.

#7158 Revert "Fix Issue 19105 - Bogus recursive template expansion via getS…
  std/traits.d
Labels: Bug Fix, auto-merge

#7268 Add closures to warning and mark warning in red.
  std/signals.d
Labels: auto-merge, documentation

#7298 Fix issue 20425: Remove Proxy.opCmp constraints
  std/typecons.d
Labels: Enhancement, auto-merge

#7282 Advance deprecation of benchmarking functionality in std.datetime
  .dscanner.ini
  std/datetime/package.d
Labels: auto-merge

#7300 Fix Issue 16223 - BigUint: undefined shift for small instantiation type
  std/internal/math/biguintcore.d
Labels: Bug Fix, auto-merge

#7304 Fix Issue 19733 - expi documentation links broken
  std/complex.d
  std/math.d
Labels: Bug Fix, auto-merge

#7285 Partial replace call to snprintf for '%a' and float or double.
  std/format.d
Labels: Bug Fix, auto-merge

#7307 Fix Issue 9588 - format prints context pointer for struct
  std/format.d
Labels: Bug Fix, auto-merge

#7225 Undeprecate JSONType member to avoid deprecation warnings
  std/json.d
Labels: Enhancement, auto-merge

#7309 Merge stable
  std/traits.d
Labels: Bug Fix, auto-merge, stable -> master

#7310 Fix Issue 18248 - radix overload of std.conv.parse fails to throw on
  std/conv.d
Labels: Bug Fix, auto-merge

#7303 Bring back "std.range.dropBack" code examples
  std/range/package.d
Labels: auto-merge, documentation

#7314 Fix Issue 20160 - ThreadInfo.cleanup() clears local thread's...
  std/concurrency.d
Labels: Bug Fix

#7313 Fix Issue 15940 - ImplicitConversionTargets and class alias in struct
  std/traits.d
  std/variant.d
Labels: Bug Fix, auto-merge

#7315 Added a style parameter to defaultGetoptFormatter.
  std/getopt.d
Labels: auto-merge

#7311 Fixes 20439: fix memoize return statement
  std/functional.d
Labels: Enhancement, auto-merge

#7305 Fix Issue 11782 - format pointer to range prints range
  std/format.d
Labels: Bug Fix, auto-merge

#7317 Fix Issue 18446 - Wrong curl onProgress examples
  std/net/curl.d
Labels: Bug Fix, auto-merge

#7284 Add automatic number conversion to std.json
  changelog/json_number_conversion.dd
  std/json.d
Labels: auto-merge

#7325 Fix Issue 15405 - FormatSpec.writeUpToNextSpec() not documented
  std/format.d
Labels: Bug Fix, auto-merge

#7320 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/json.d
Labels: Bug Fix

#7296 Make std.bigint `@safe`
  changelog/bigint-safe.dd
  std/bigint.d
  std/internal/math/biguintcore.d
  std/internal/math/biguintx86.d
Labels: auto-merge

#7328 Fix unittest, which assumed real exponents having at least 15 bit.
  std/numeric.d
Labels: auto-merge

#7329 Fix unittest, which assumes real > double.
  std/numeric.d
Labels: auto-merge

#7321 Fix Issue 5628 - std.math unittest disabled - roundoff error in pow()
  std/math.d
Labels: Bug Fix, auto-merge

#7330 Provide a complete description of dirName output
  std/path.d
Labels: auto-merge, documentation

#7336 Fix Issue 20259 - [Function Socket.bind] Doesn't inform what Exception it throws
  std/socket.d
Labels: Bug Fix, auto-merge

#7334 Fix Issue 5232 - [patch] std.conv.to & std.conv.roundTo report invalid overflows for very large numbers
  std/conv.d
Labels: Bug Fix

#7151 std.bigint.BigInt: allow casting to floating point numbers
  std/bigint.d
Labels: Enhancement, WIP, auto-merge

#7335 Add further example for std.normalize
  std/numeric.d
Labels: auto-merge

#7319 Fix Issue 17427 - std.concurrency internal errors on uninitialised mailbox
  std/concurrency.d
Labels: Bug Fix, auto-merge

#7241 Add isClose, a replacement for approxEqual
  std/math.d
Labels: auto-merge

#7338 Fix Issue 12461 - Typedef and opOpAssign
  std/typecons.d
Labels: Bug Fix, auto-merge

#7341 Disable `make install` for the Darwin_64_32 target on the auto-tester
  posix.mak
Labels: auto-merge
