Repository dlang/phobos, pull requests merged in 2019-11, with the labels that each got.

#7261 Allow user to override number of threads in circleci script
  .circleci/run.sh
Labels: auto-merge

#7230 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/unconst.dd
  std/format.d
Labels: Bug Fix, auto-merge

#7190 adds assert messages for container.array
  std/container/array.d
Labels: auto-merge-squash

#7263 Fix Issue 20357 - format should obey space flag when printing nan or inf
  std/format.d
Labels: Bug Fix, auto-merge

#7270 Fix Issue 10902 - some phobos unittests take an excessive amount of time
  std/algorithm/setops.d
  std/parallelism.d
  std/process.d
  std/random.d
Labels: Bug Fix

#7269 [posix.mak]: Build @betterC extracted tests without -unittest
  posix.mak
Labels: Blocking Other Work, auto-merge

#7266 Made SortedRange verifications conditionally compiled.
  std/range/package.d
Labels: auto-merge, betterC

#7272 Merge stable
  posix.mak
  std/range/package.d
Labels: auto-merge, stable -> master

#7276 Fix Issue 11013 - ignoring variable inside the predicate of find
  std/algorithm/searching.d
Labels: Bug Fix, auto-merge

#7242 Remove multidisk support completely from zip.std.
  std/zip.d
Labels: auto-merge

#7275 Fix Issue 10126 - Make TaskPool terminate on its own or improve docs
  std/parallelism.d
Labels: Bug Fix

#7289 Fix Issue 20408 - style checker should not check backup files
  posix.mak
Labels: Bug Fix, auto-merge

#7287 Replace throw exception by enforce and add unittests.
  std/zip.d
Labels: auto-merge

#7290 Change Posix to POSIX in comments of std.file.
  std/file.d
Labels: Trivial, auto-merge

#7255 Rework documentation of std.zip.
  .dscanner.ini
  std/zip.d
Labels: auto-merge

#7291 Add missing backquote in binaryReverseArgs changelog
  changelog/binaryReverseArgs.dd
Labels: auto-merge

#7288 Clarify the behaviour of rename on posix systems.
  std/file.d
Labels: auto-merge

#7253 Fix issue 20314: pass `only` parameters by value
  std/range/package.d
Labels: Bug Fix, auto-merge

#7295 Make Pid.osHandle nogc
  std/process.d
Labels: auto-merge

#7294 prevent cases of illegal implicit convertions in CaseStatement
  std/math.d
Labels: auto-merge

#7176 Fix Issue 20198 - Make std.math.nextUp and nextDown and nextafter work in CTFE for float and double
  std/math.d
Labels: Enhancement, auto-merge, math

#7279 std.zip: Remove some unnecessary private variables
  std/zip.d
Labels: Bug Fix, auto-merge
