Repository dlang/phobos, pull requests merged in 2019-06, with the labels that each got.

#7056 Add a sponsorship button
  .github/FUNDING.yml
Labels: auto-merge

#7059 std.process.forkChild cannot be inlined
  std/process.d
Labels: auto-merge

#7046 assert messages for std.format
  std/format.d
Labels: 72h no objection -> merge, auto-merge

#7061 Variant of an array can be compared with another array
  std/variant.d
Labels: Bug Fix, auto-merge

#7064 function attributes go on the right of function aliases
  std/datetime/timezone.d
Labels: Blocking Other Work, Trivial

#7066 [docs][std.range.primitives] Add links to array range primitives
  std/range/primitives.d
Labels: auto-merge

#7057 Add `inout` to range.front to reduce template proliferation
  std/range/primitives.d
Labels: 72h no objection -> merge, auto-merge

#7069 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/algorithm/iteration.d
  std/math.d
  std/random.d
Labels: Bug Fix

#7068 Fix issue 19939 - std.format count width error
  std/format.d
Labels: Bug Fix, auto-merge

#7081 Increase unit-test coverage of complex.d to 100 percent
  std/complex.d
Labels: auto-merge-squash

#7082 19987 - Reduce memory used by VariantN
  std/variant.d
Labels: Bug Fix, auto-merge

#7083 typo in transcode unittest
  std/encoding.d
Labels: auto-merge

#7074 std_json allow trailing comma
  changelog/std_json_trailing_comma.dd
  std/json.d
Labels: 72h no objection -> merge, auto-merge

#7085 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/format.d
Labels: Bug Fix, auto-merge, stable -> master

#7072 Fix issue 19823 - std.range.dropOne doesn't drop the element when cal…
  std/algorithm/iteration.d
Labels: Bug Fix, auto-merge

#7087 Adds assert messages
  std/algorithm/comparison.d
Labels: auto-merge

#7088 Adds assert messages
  std/algorithm/iteration.d
Labels: auto-merge

#7090 Addes assert messages
  std/algorithm/setops.d
Labels: auto-merge

#7091 Adds assert messages to std.algorithm.sorting
  std/algorithm/sorting.d
Labels: auto-merge

#7060 [Breaking] Deprecate `alias get this` in Nullable.
  changelog/remove-nullable-alias-get-this.dd
  std/typecons.d
Labels: auto-merge

#7092 Fix blocking issue in std/experimental/allocator/building_blocks/region.d
  std/experimental/allocator/building_blocks/region.d
Labels: auto-merge

#7089 Adds asserts messages
  std/algorithm/searching.d
Labels: auto-merge

#7063 Make ErrnoException.errno nothrow pure @nogc @safe
  changelog/errnoexception-errno-attributes.dd
  std/exception.d
Labels: 72h no objection -> merge, auto-merge

#7079 Issue 19983 - Add fast path using slice assignment to std.internal.cstring.tempCString
  std/internal/cstring.d
Labels: Enhancement, auto-merge, optimization

#7094 Fix enum type in std.socket to match the receiver type
  std/experimental/allocator/building_blocks/stats_collector.d
  std/parallelism.d
  std/socket.d
Labels: auto-merge

#5776 Fix Issue 16487 - Add function to obtain the available disk space
  changelog/std-file-getAvailableDiskSpace.dd
  std/file.d
Labels: Enhancement, auto-merge-squash
