Repository dlang/phobos, pull requests merged in 2019-09, with the labels that each got.

#7163 get rid of some GC allocations in `sformat` and `formatElement`
  std/format.d
Labels: auto-merge

#7164 Fix Issue 20186 - File size of "Hello, world" executable increased by 185KB
  .dscanner.ini
  std/array.d
Labels: Bug Fix, auto-merge, optimization

#7168 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/array-opslice.dd
  changelog/errnoexception-errno-attributes.dd
  changelog/remove-nullable-alias-get-this.dd
  changelog/std-file-getAvailableDiskSpace.dd
  changelog/std_json_trailing_comma.dd
Labels: auto-merge

#7170 Fix Issue 20192 - Make std.math.isSubnormal work in CTFE
  std/math.d
Labels: Enhancement, auto-merge

#7169 Fix Issue 17705 - std.math.isFinite cannot run at compile-time
  std/math.d
Labels: Bug Fix, auto-merge, math

#7172 Fix Issue 20147 - Enable comparison (==, >, >=, <=, <) between std.bigint.BigInt and floating point numbers
  std/bigint.d
Labels: Enhancement, auto-merge

#7174 Fix issue 19514 - gcd(BigInt(2), BigInt(1)) fails
  std/numeric.d
Labels: Bug Fix, auto-merge

#7179 Fix issues 20202 & 20203 - Make std.math.signbit and copysign work in CTFE
  std/math.d
Labels: Enhancement, auto-merge, math

#7175 Fix Issue 20196 - Make std.math.isNormal work in CTFE
  std/math.d
Labels: Enhancement, auto-merge, math

#7178 Fix Issue 20201 - Make std.math.scalbn pure
  std/math.d
Labels: Enhancement, auto-merge, math

#7177 Fix issues 20199 & 20200: make std.math.frexp & isPowerOf2 work in CTFE
  std/math.d
Labels: Enhancement, auto-merge, math

#7184 bigint.d: replace Error with assert()
  std/bigint.d
Labels: auto-merge

#7185 Fix issue 20218: format: don't try to print the entire range while merely testing the format string
  std/format.d
Labels: Bug Fix, auto-merge

#7186 Fix issue 20145 - Random unittest failures in std.datetime.stopwatch
  std/datetime/stopwatch.d
Labels: Bug Fix, auto-merge

#7191 adds assert messages to std.container.dlist
  std/container/dlist.d
Labels: auto-merge

#7192 assert messages container dlist typo fix
  std/container/dlist.d
Labels: auto-merge

#7165 Add Unconst to std.traits
  changelog/unconst.dd
  std/traits.d
Labels: auto-merge

#7193 FiberScheduler: Make the stack size configurable
  std/concurrency.d
Labels: auto-merge

#7195 Make task() example compilable.
  std/parallelism.d
Labels: auto-merge

#7196 Remove posix only unittest relying on presence of unzip untility.
  std/zip.d
Labels: auto-merge

#7180 Clearer documentation for approxEqual
  std/internal/test/dummyrange.d
  std/math.d
Labels: auto-merge

#7199 std.zip: Update and correct main documentation
  std/zip.d
Labels: auto-merge

#7203 Fix typo.
  std/xml.d
Labels: auto-merge

#7204 Move "print" to "convert" in example of to template.
  std/conv.d
Labels: auto-merge

#7202 std.zip: Add data structure for detecting overlapping chunks.
  std/zip.d
Labels: auto-merge

#7206 typetuple: 100% code coverage
  std/typetuple.d
Labels: auto-merge
