Repository dlang/phobos, pull requests merged in 2019-07, with the labels that each got.

#7096 Make locally-defined `FiberScheduler` actually usable
  std/concurrency.d
Labels: auto-merge-squash

#7075 Implement Phobos side of DIP1014
  std/algorithm/mutation.d
  std/traits.d
Labels: auto-merge

#7097 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/asciicontroltable.dd
  changelog/count_processors_via_sched_affinity_on_linux.dd
  changelog/new_schwartzSort_overload.dd
  changelog/phobos-dip1000.dd
Labels: auto-merge

#7098 Replace D1 operator overloads with D2 operator overloads
  std/bigint.d
  std/bitmanip.d
  std/internal/math/biguintcore.d
  std/variant.d
  std/xml.d
Labels: auto-merge

#7099 Replace D1 operator overloads with D2 operator overloads - Part 2
  std/bitmanip.d
Labels: auto-merge

#7093 Clarified error when trying to convert NaN
  std/conv.d
Labels: auto-merge

#7076 Fix Issue 19979 - std.regex should return null instead of zero-length slice for non-matched captures
  std/regex/internal/ir.d
  std/regex/package.d
Labels: Enhancement, auto-merge

#7077 Fix Issue 19980 - File.byLine skips first line in some cases when used inside map!()
  std/stdio.d
Labels: Bug Fix, auto-merge

#7054 Avoid mulu in std.container.array.Array!T when T.sizeof == 1
  std/container/array.d
Labels: auto-merge

#7101 Fix issue 19834 - File exception for [std.file.copy] on windows shows the target file rather than the source file
  std/file.d
Labels: Enhancement, auto-merge

#7084 Fix issue 19994 - Can't nest self-referential Algebraic types
  std/typecons.d
  std/variant.d
Labels: Enhancement, auto-merge

#7080 Fix issue 19986 - Can't assign large const T to std.Variant.VariantN
  std/variant.d
Labels: Bug Fix, auto-merge

#7100 Fix Issue 19105 - Bogus recursive template expansion via getSymbolsByUDA
  std/traits.d
Labels: Bug Fix, auto-merge

#7006 Fix Issue 19838 - RefCounted fails to instantiate due to pureness of …
  std/algorithm/mutation.d
Labels: Enhancement, auto-merge

#7106 Fix issue 20043: support Tuple.rename on const tuples
  std/typecons.d
Labels: Enhancement

#7110 Replace usages of `in` with `const scope`
  std/file.d
Labels: auto-merge

#7109 std.math: change tests for rounding
  std/file.d
  std/math.d
Labels: Blocking Other Work, auto-merge

#7107 Get make!T to compile when T is a shared value type
  std/experimental/allocator/package.d
Labels: Bug Fix, auto-merge

#7113 std.algorithm.sorting: fix typo in pivotPartition
  std/algorithm/sorting.d
Labels: auto-merge

#7114 Fix issue 20070 - std.conv.toImpl matches two functions when using st…
  std/conv.d
Labels: Bug Fix, Enhancement, auto-merge

#7102 Turn on -preview=markdown
  etc/c/curl.d
  etc/c/sqlite3.d
  posix.mak
  std/algorithm/comparison.d
  std/experimental/allocator/building_blocks/package.d
  std/experimental/checkedint.d
  std/functional.d
  std/math.d
  std/parallelism.d
  std/path.d
  std/range/package.d
  std/regex/package.d
  std/typecons.d
  std/uni.d
Labels: auto-merge

#7115 Add comment for using non async-signal-safe function
  std/process.d
Labels: auto-merge

#7105 Addes assert messages to bitmanip
  std/bitmanip.d
Labels: auto-merge

#7117 std.range.enumerate should work with a non-mutable start index
  std/range/package.d
Labels: Enhancement, auto-merge
