Repository dlang/phobos, pull requests merged in 2020-07, with the labels that each got.

#7550 Remove invalid alias from chain's implementation
  std/range/package.d
Labels: auto-merge

#7487 std.math: Begin deprecation of accidentally leaked AliasSeq
  std/math.d
Labels: Bug Fix, auto-merge

#7552 Fix issue 21021 - std.variant confused by alias this when struct larg…
  std/variant.d
Labels: Bug Fix, auto-merge

#7542 std.meta: Fix wrong assert for Issue #20863
  std/meta.d
Labels: auto-merge

#7553 bitmanip: make use of new byteswap() function
  std/bitmanip.d
Labels: auto-merge, refactoring

#7554 Move stableRemove alias to correct place for documentation
  std/container/dlist.d
Labels: Easy Review, auto-merge, documentation

#7555 Fix bug 12521: update docs to match current getopt behaviour.
  std/getopt.d
Labels: Bug Fix

#7518 Faster staticMap and Filter
  std/meta.d
Labels: auto-merge

#7558 std.digest.sha1: don't reinvent bswap()
  std/digest/sha.d
Labels: auto-merge, refactoring

#7557 Clarify getopt behavior with arraySep.
  std/getopt.d
Labels: Easy Review, auto-merge, documentation

#7559 std.digest.sha: don't reinvent rotate functions
  std/digest/sha.d
Labels: auto-merge, refactoring

#7562 sha: inline critical functions
  std/digest/sha.d
Labels: auto-merge

#7564 sha: bswap without intermediate conversion to byte array
  std/digest/sha.d
Labels: auto-merge

#7568 unsignedToTempString: use the template version
  std/conv.d
  std/random.d
  std/utf.d
Labels: auto-merge

#7538 [stable] Relax some new std.complex unittests for double-precision real
  std/complex.d
Labels: auto-merge

#7569 Reduce default template instantiations
  std/uni/package.d
Labels: auto-merge

#7571 Fix issue 21088: move alias statement into staticMap mixin body.
  std/meta.d
Labels: Bug Fix, auto-merge

#7572 std.getopt: Fix link to perl docs
  std/getopt.d
Labels: auto-merge
