Repository dlang/phobos, pull requests merged in 2020-02, with the labels that each got.

#7371 adding assert messages to std.container.slist
  std/container/slist.d
Labels: Easy Review, auto-merge

#7369 adding assert messages to std.container.binary_heap
  std/container/binaryheap.d
Labels: Easy Review, auto-merge

#7372 adding assert messages to std.conv
  std/conv.d
Labels: Easy Review, auto-merge

#7370 adding assert messages to rbtree
  std/container/rbtree.d
Labels: Easy Review, auto-merge

#7388 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/format.d
  std/json.d
Labels: Bug Fix, auto-merge

#7389 [Trivial] Issue 12931: Move shared to the RHS
  std/traits.d
Labels: Trivial, auto-merge

#7390 Issue 20548 followup: in 32-bit builds RandomCoverChoices allocates more memory than needed for the bit vector
  std/random.d
Labels: auto-merge

#7391 std.socket: Move const to the RHS
  std/socket.d
Labels: auto-merge

#7377 Fix std.format FP printing for soft-float targets
  .dscanner.ini
  std/format.d
Labels: 72h no objection -> merge

#7318 Partial replace call to snprintf for '%e' and float or double.
  std/format.d
Labels: auto-merge

#7395 Update D-Scanner to >0.8.0
  .dscanner.ini
  posix.mak
Labels: auto-merge

#7393 fix Issue 20566 - std.sformat should avoid allocating memory when pri…
  std/format.d
Labels: Enhancement, auto-merge

#7396 [docs] update deprecation schedule
  std/datetime/stopwatch.d
Labels: auto-merge

#7397 Fix Issue 20585 - std.stdio.File.open() failure leaves File in invalid
  std/stdio.d
Labels: Bug Fix, auto-merge

#7399 [Trivial] Remove obsolete hack in std.internal.math.biguintcore
  std/internal/math/biguintcore.d
Labels: Trivial, auto-merge

#7400 Fix recent test regressions for targets with double-precision real
  std/conv.d
  std/math.d
Labels: auto-merge

#7402 zip.d: fix printf formats
  std/zip.d
Labels: Blocking Other Work, Easy Review, auto-merge

#7403 more printf format fixes
  std/format.d
  std/internal/math/biguintcore.d
  std/zip.d
Labels: Blocking Other Work

#7404 unittest.d: printf formats
  unittest.d
Labels: Blocking Other Work, auto-merge

#7405 Fix Issue 20606 - Cannot cast non-mutable BitArray to void[], size_t[]
  std/bitmanip.d
Labels: Bug Fix, auto-merge

#7392 Added a chmod example in the description...
  std/file.d
Labels: auto-merge

#7398 Fix issue 20589 - typeof may give wrong result in case of classes defining `opCall` operator
  std/container/array.d
  std/conv.d
Labels: Bug Fix, auto-merge

#7406 Merge remote-tracking branch 'upstream/stable' into merge_stable
  std/stdio.d
Labels: Bug Fix, auto-merge
