Repository dlang/phobos, pull requests merged in 2020-04, with the labels that each got.

#7281 Remove deprecated symbols from std.digest.digest
  changelog/digest.dd
  std/digest/crc.d
  std/digest/digest.d
  unittest.d
Labels: auto-merge

#7438 Fix incorrect use of sprintf format
  std/math.d
Labels: auto-merge

#7439 Remove version(assert) from TimSort
  std/algorithm/sorting.d
Labels: auto-merge

#7440 Enable `@safe` on `cartesianProduct`'s `Result.popFront`
  std/algorithm/setops.d
Labels: auto-merge

#7443 Fix 20733. Remove docs about copy construction from hasElaborateAssign.
  std/traits.d
Labels: Bug Fix, auto-merge, documentation

#7442 Fix issue 20732. Do not invoke any complex copy construction for swap
  std/algorithm/mutation.d
Labels: Enhancement, auto-merge

#7446 Follow up review on PR 7441
  std/algorithm/iteration.d
  std/container/rbtree.d
  std/conv.d
  std/internal/cstring.d
Labels: auto-merge

#7447 std.range.primitives: Fix static condition for X32 targets
  std/range/primitives.d
Labels: Easy Review

#7437 Add get(default) same-type overload in Nullable
  std/typecons.d
Labels: auto-merge

#7436 std.random.unpredictableSeed: on x86/x86-64 try using RDRAND when there is no arc4random
  std/random.d
Labels: 72h no objection -> merge, Enhancement, auto-merge

#7450 [dmd-cxx] Appender and RefAppender: use opSlice() instead of data()
  std/array.d
Labels: Easy Review

#7451 specify return type for SortedRange.opBinaryRight!"in"
  std/range/package.d
Labels: Trivial, auto-merge, documentation

#7452 Fix/issue 20755 implicitconversiontargets const class
  std/traits.d
Labels: Enhancement, auto-merge

#7454 Fix Issue 20743 - Checked!(int, Abort) does not abort but raise SIGFPE
  std/experimental/checkedint.d
Labels: Bug Fix, auto-merge

#7457 Fix Issue 20751 - SortedRange with ref predicate parameters fails
  std/algorithm/sorting.d
  std/range/package.d
Labels: Bug Fix, auto-merge

#7459 Fix Issue 20496 - chunkby should support ref predicate
  std/algorithm/iteration.d
Labels: Enhancement, auto-merge

#7460 Changelog fix: std.digest is not going to be removed, std.digest.digest is
  changelog/digest.dd
Labels: Trivial, auto-merge, documentation

#7458 Fix Issue 20426 - doesPointTo with void[N] fails
  std/exception.d
Labels: Bug Fix, auto-merge

#7461 Don't rely on implicit conversion of int to fp for args to intrinsic …
  std/math.d
Labels: Trivial, auto-merge

#7464 Fix issue 20782 - allow std.conv.to to convert string to const enum
  std/conv.d
Labels: Bug Fix, auto-merge

#7465 Fix Issue 20783 - std.string.lastIndexOf doesn't work correctly in CTFE
  std/string.d
Labels: 72h no objection -> merge, Bug Fix
