Repository dlang/phobos, pull requests merged in 2020-10, with the labels that each got.

#7647 Update header of sqlite3 to 3.33.0
  etc/c/sqlite3.d
Labels: auto-merge

#7646 Issue 21250 - dirEntries on non-existent directory causes assert error
  std/file.d
  std/typecons.d
Labels: Bug Fix, auto-merge-squash

#6469 fix issue 18789 - std.stdio messes up UTF conversions on output
  std/stdio.d
Labels: Bug Fix, auto-merge

#7463 Mostly fix 18559: std.math.* should stop using real overloads by default
  std/bigint.d
  std/math.d
Labels: auto-merge

#7652 Fix issue 21296 - std.variant.Variant cannot be initialized with immu…
  std/variant.d
Labels: auto-merge

#7653 [stable] allocator_list unittests: Use core.memory.pageSize instead of minimumPageSize
  std/experimental/allocator/building_blocks/allocator_list.d
Labels: auto-merge

#7655 Fix issue 13930, 19345 - Fix `receiveOnly` for non-assignable types
  std/concurrency.d
Labels: Bug Fix, auto-merge

#7657 Revert "Fix issue 13930, 19345 - Fix `receiveOnly` for non-assignable types "
  std/concurrency.d
Labels: auto-merge

#7658 Fix issue 21302: std.uni's documentation contains a dead link to its …
  std/uni/package.d
Labels: Bug Fix, Easy Review, Trivial, auto-merge

#7660 fix crash: keep a copy of the return value of setlocale(), it can become invalid
  std/stdio.d
Labels: auto-merge

#7661 Fix issue 13930, 19345 - Fix `receiveOnly` for non-assignable types
  std/concurrency.d
  std/variant.d
Labels: Bug Fix, auto-merge

#7664 merge stable
  std/experimental/allocator/building_blocks/allocator_list.d
  std/file.d
  std/typecons.d
Labels: auto-merge

#7667 [LDC] move `pragma(inline, true);` out of function bodies
  std/math.d
Labels: auto-merge

#7665 math: remove unused code inside of unittest block
  std/internal/math/biguintcore.d
Labels: auto-merge

#7666 Improve written bash `run.sh` script
  .circleci/run.sh
Labels: auto-merge

#7662 Add Cirrus CI
  .cirrus.yml
Labels: auto-merge

#7671 std.math: Fix log coefficiants for 128-bit implementation
  std/math.d
Labels: Blocking Other Work, auto-merge, math

#7624 Make Phobos compilable with preview=fieldwise
  std/variant.d
Labels: Bug Fix, auto-merge

#7672 std.complex: Relax some more unittests for floating point precision on ARM64
  std/complex.d
Labels: auto-merge, math

#7673 Incorrect link to info about discriminating union
  std/variant.d
Labels: auto-merge

#7676 std.stdio: move std.process import inside unittest
  std/stdio.d
Labels: auto-merge

#7674 Fix Issue 21337: Join can iterate ranges multiple times
  std/array.d
Labels: Bug Fix, Enhancement, auto-merge

#7679 timezone: wrap dirEntries foreach in a trusted lambda instead of making the whole function @trusted
  std/datetime/timezone.d
Labels: auto-merge

#7682 math: mark tan as @safe instead of @trusted
  std/math.d
Labels: auto-merge

#7681 stdio: optimize readln algorithm for non-char type
  std/stdio.d
Labels: auto-merge

#7678 regex: partially make regex pure
  std/regex/internal/backtracking.d
  std/regex/internal/ir.d
  std/regex/internal/thompson.d
  std/regex/package.d
Labels: auto-merge

#7683 std.functional: simplify compose
  std/functional.d
Labels: auto-merge

#7685 Fix issue 6484 - compose can't take multi arg functions
  std/functional.d
Labels: Enhancement, auto-merge

#7686 Fix issue 21347 - std.functional.adjoin should work in BetterC
  std/functional.d
Labels: Enhancement, auto-merge

#7675 Fix Issue 18157 - std.file.rmdirRecurse should be usable in @safe
  std/file.d
Labels: auto-merge

#7637 Fix issue 21253 - Can't compile Variant.visit!(...) with generic func…
  std/variant.d
Labels: Bug Fix, auto-merge
