Repository dlang/phobos, pull requests merged in 2020-05, with the labels that each got.

#7462 Followup to #7458 - Always return true for mayPointTo if the void[N] …
  std/exception.d
Labels: auto-merge

#7468 Make std.uni a package
  posix.mak
  std/uni/package.d
  win32.mak
  win64.mak
Labels: auto-merge

#7471 Fix Issue 20799 - schwartzSort does not pin transformation results wi…
  std/algorithm/sorting.d
Labels: Bug Fix, auto-merge

#7472 merge stable
  changelog/digest.dd
Labels: auto-merge

#7456 std.complex: Add complex exp(), log(), log10(), and pow()
  std/complex.d
  std/package.d
Labels: auto-merge, math

#7474 std.complex: Add complex tan()
  std/complex.d
Labels: auto-merge, math

#7478 Add tests for empty empty static arrays of (|w|d)char's
  std/format.d
Labels: auto-merge

#7477 merge stable
  changelog/date-isoweek.dd
  changelog/deprecate-xml.dd
  changelog/digest.dd
  std/algorithm/sorting.d
Labels: Bug Fix, auto-merge

#7479 [Trivial] Use std.meta instead of std.typetuple
  std/algorithm/sorting.d
Labels: Trivial, auto-merge

#7476 Mark BigInt.toHash `pure` `@nogc`
  std/bigint.d
Labels: attributes, auto-merge

#7473 std.math: Remove deprecated creal functions
  std/complex.d
  std/math.d
Labels: auto-merge, math

#7482 std.math: Implement isClose for std.complex types
  std/complex.d
  std/math.d
Labels: math

#7483 Restore accidentally removed import from std.math
  std/math.d
Labels: auto-merge

#7484 std.experimental.allocator: use core.bitop for trailingZeroes and leadingOnes
  std/experimental/allocator/building_blocks/bitmapped_block.d
  std/experimental/allocator/common.d
Labels: Easy Review, auto-merge

#7475 std.complex: Add complex norm() and proj()
  std/complex.d
Labels: auto-merge, math

#7486 [dmd-cxx] Backport fixes from #6752 and #7196
  std/net/curl.d
  std/zip.d
Labels: Bug Fix, Easy Review

#7485 fix Issue 20836 - std.math: reorder declarations from most visible to least
  std/math.d
Labels: Bug Fix, auto-merge, refactoring

#7466 std.file.setTimes: on macOS use setattrlist to avoid truncating timestamp precision to microseconds
  std/file.d
Labels: Bug Fix, auto-merge

#7488 std.typecons: Fix inconsistent indentation in Nullable implementation
  std/typecons.d
Labels: Trivial, auto-merge

#7491 speed up instantation of Reverse and Filter templates
  std/meta.d
Labels: Easy Review, auto-merge

#7490 speed up instantiation of Filter and staticMap templates
  std/meta.d
Labels: Easy Review, auto-merge

#7492 [Trivial] Ddoc: Fix refs to core.stdc.stdio.stdin/stdout/stderr in stdio.d
  std/stdio.d
Labels: Trivial

#7489 Fix issue 20850 - Can't assign enum of Tuple
  std/typecons.d
Labels: Bug Fix, auto-merge

#7493 std.traits: FunctionAttribute supports live function
  std/traits.d
Labels: auto-merge

#7434 std.socket: Improve 16514 unittest to guard against inherited attributes
  std/socket.d
Labels: auto-merge

#7360 Fix Issue 9298 - some std.math functions not implemented for Win64
  std/math.d
Labels: auto-merge

#7494 Replace template AliasSeq with a simple alias
  std/meta.d
Labels: Trivial, auto-merge, refactoring

#7496 Simplify isSame and Pack
  std/meta.d
Labels: auto-merge

#7497 staticMap: explain design
  std/meta.d
Labels: Trivial, auto-merge

#7504 Fix issue 19525 - Duration is not usable with zero-arg std.algorithm.sum
  std/algorithm/iteration.d
Labels: Enhancement, auto-merge

#7508 fix issue 20882 - Outdated examples in the documentation (std.stdio)
  std/stdio.d
Labels: Enhancement, auto-merge

#7502 Fix Issue 20869 - `move` is overly trusting of `opPostMove`
  .dscanner.ini
  std/algorithm/mutation.d
Labels: Enhancement, auto-merge

#7509 Improve speed of std.digest.digest!(Hash, Range) on non-array ranges
  std/digest/package.d
Labels: Enhancement, auto-merge, optimization

#7500 alias FSChar = char for a wider range of platforms
  std/stdio.d
Labels: auto-merge

#7503 Fix Issue 20874 - std.json.assign requires '@safe' and 'pure'
  std/json.d
Labels: Bug Fix, auto-merge
