Repository dlang/phobos, pull requests merged in 2020-06, with the labels that each got.

#7512 [std.stdio.writeln] Simplify static checks for string specialization
  std/stdio.d
Labels: auto-merge

#7514 merge stable
  std/file.d
Labels: Bug Fix, auto-merge

#7517 scalbn() doesn't inline
  std/math.d
Labels: Blocking Other Work, auto-merge

#7516 Fix documentation of std.math.isIdentical for NaN: compares all bits not just payload
  std/math.d
Labels: auto-merge, documentation

#7520 std.math: Fix comment for isIdentical
  std/math.d
Labels: auto-merge

#7521 [dmd-cxx] Don't shorten the width of the iteration variable
  std/range/package.d
Labels: auto-merge

#7526 Remove FUNDING.yml
  .github/FUNDING.yml
Labels: Trivial, auto-merge

#7527 merge stable
  std/math.d
Labels: auto-merge

#7532 Issue 20928 - Overloaded opIndex confuses MapResult
  std/algorithm/iteration.d
Labels: Bug Fix, auto-merge

#7519 Let safety of cartesianProduct.Result.popFront be inferred
  std/algorithm/setops.d
Labels: Bug Fix

#7535 fix issue 20949 - std.range.popFront is unsafe in release mode
  std/range/primitives.d
Labels: Bug Fix, auto-merge

#7530 Fix issue 20929 - std.experimental.allocator.expandArray's range-based overload fails to instantiate for char and wchar arrays.
  std/experimental/allocator/package.d
Labels: Bug Fix

#7511 Support construction of std.bigint.BigInt from a sign and a byte-array magnitude
  std/bigint.d
  std/internal/math/biguintcore.d
Labels: Enhancement, auto-merge

#7541 merge stable
  std/algorithm/setops.d
Labels: Bug Fix, auto-merge

#7548 Fix public examples failing due to missing imports
  std/experimental/checkedint.d
  std/typecons.d
Labels: Trivial, auto-merge

#7533 [std.meta] Improve AliasSeq Map example & other tweaks
  std/meta.d
Labels: auto-merge
