Repository dlang/phobos, pull requests merged in 2020-08, with the labels that each got.

#7573 Replace is(Unqual!T == Unqual!U) with is(immutable T == immutable U) for speed & memory usage
  std/algorithm/comparison.d
  std/algorithm/iteration.d
  std/algorithm/searching.d
  std/array.d
  std/bigint.d
  std/container/array.d
  std/conv.d
  std/csv.d
  std/datetime/interval.d
  std/datetime/systime.d
  std/datetime/timezone.d
  std/encoding.d
  std/experimental/allocator/package.d
  std/experimental/logger/core.d
  std/file.d
  std/format.d
  std/internal/math/biguintcore.d
  std/internal/test/dummyrange.d
  std/json.d
  std/math.d
  std/net/isemail.d
  std/numeric.d
  std/path.d
  std/range/primitives.d
  std/regex/package.d
  std/stdio.d
  std/string.d
  std/traits.d
  std/uni/package.d
  std/utf.d
  std/uuid.d
Labels: auto-merge

#7576 Replace Unqual-based idiom with immutable-based idiom
  std/array.d
  std/bitmanip.d
  std/format.d
  std/random.d
  std/stdio.d
  std/variant.d
Labels: auto-merge-squash

#7577 Work around issue 21111: Temporarily disable inlining of T_SHA2_16_79
  std/digest/sha.d
Labels: auto-merge

#7578 Fix issue 21113: Use sysctl for thisExePath on BSD.
  std/file.d
Labels: Enhancement, auto-merge

#7580 Improve behavior of std.socket "soft" unittests
  std/socket.d
Labels: auto-merge

#7583 Fix 21131 -- proper handling of non-dchar appending to Appender!wstring and Appender!dstring
  std/array.d
  std/utf.d
Labels: Enhancement, auto-merge

#7585 Make the style checks run first
  posix.mak
Labels: Easy Review, auto-merge

#7586 Add makefile target for testing with no autodecode.
  posix.mak
Labels: auto-merge, no autodecode

#7587 merge stable
  std/complex.d
Labels: auto-merge

#7455 Fix Issue 20765 - Can't run processes with relative paths when specif…
  std/process.d
Labels: Bug Fix, auto-merge

#7588 Update random.d
  std/random.d
Labels: auto-merge

#7581 Fix Issue 20984 - Heisenbug: FreeBSD64 Phobos random test suite failu…
  std/process.d
Labels: Bug Fix, auto-merge

#7589 fix issue 21148, possible failure of CI when testing nano precision of file time stamps
  std/file.d
Labels: Bug Fix, auto-merge-squash

#7591 Prepare for properly parsed float/double literals
  std/conv.d
  std/internal/math/errorfunction.d
  std/internal/math/gammafunction.d
  std/math.d
Labels: Blocking Other Work, Trivial, auto-merge, refactoring

#7592 std.math: Enable proper single- and double-precision ldexp overloads
  std/math.d
Labels: auto-merge

#7590 Fix issue 7033: File.rawWrite is slow on Windows
  std/stdio.d
Labels: Bug Fix, auto-merge-squash

#7593 UUID: Replace 'in ref' overloads with 'const scope ref'
  std/uuid.d
Labels: auto-merge

#7594 Change Socket constructor to accept its parameter by const scope
  std/socket.d
Labels: auto-merge

#7596 Bump HOST_DMD_VERSION on Azure to avoid the gc segfault
  azure-pipelines.yml
Labels: auto-merge

#7595 Make it so std.utf can be tested with no autodecoding.
  posix.mak
  std/algorithm/comparison.d
  std/array.d
  std/range/primitives.d
  std/utf.d
Labels: auto-merge, no autodecode

#7584 Fix issue 21129: Make `OnlyResult` store a value tuple instead of a static array of CommonType.
  std/range/package.d
Labels: Bug Fix, auto-merge

#7598 Reduce the number of isAggregateType!T checks
  std/ascii.d
  std/format.d
  std/range/primitives.d
  std/traits.d
Labels: auto-merge

#7597 structure SSSE3 array of constants
  std/internal/digest/sha_SSSE3.d
Labels: Blocking Other Work, auto-merge

#7606 Fix issue 21199: call `unaryFun!fun` in `Nullable.apply` to support string parameter.
  std/typecons.d
Labels: Bug Fix, auto-merge

#7607 Fix Issue 21201 - let std.uuid.parseUUID accept input ranges whose elements are char or wchar, not just dchar
  std/uuid.d
Labels: Enhancement, auto-merge

#7525 Remove an unnecessary allocation from BigInt powmod
  std/bigint.d
Labels: auto-merge

#7608 std.typecons : AutoImplement: Handle 'in' storage class
  std/typecons.d
Labels: Bug Fix, auto-merge

#7605 min must be stable
  std/algorithm/comparison.d
Labels: Bug Fix, auto-merge

#7610 Cherry-pick auto-decoding Makefile changes to stable
  posix.mak
Labels: Blocking Other Work, auto-merge, no autodecode, stable-priority

#7611 Revert "std.traits: Adapt unittest to pass with `-preview=in`"
  std/traits.d
Labels: auto-merge

#7612 Fix 21210: std.traits : isAssignable false positive on disabled copy struct
  std/traits.d
Labels: Bug Fix, auto-merge

#7614 std.traits: Adapt unittest to pass with `-preview=in`
  std/traits.d
Labels: auto-merge
