Repository dlang/phobos, pull requests merged in 2020-03, with the labels that each got.

#7410 Typo fix in Systime describtion
  std/datetime/systime.d
Labels: auto-merge

#7411 Make BitArray.count() const.
  std/bitmanip.d
Labels: auto-merge

#7412 fix azure pipeline: building with LDC now needs DMD as a host compile…
  azure-pipelines.yml
Labels: auto-merge

#7414 fix azure pipeline: building with LDC now needs DMD as a host compile…
  azure-pipelines.yml
Labels: auto-merge

#7407 Allow floatTraits to work with inout
  std/math.d
Labels: auto-merge

#7409 Fix @betterC testsuite
  posix.mak
  std/range/package.d
  std/typecons.d
Labels: betterC

#7355 Add initial support for iOS, tvOS and watchOS
  std/datetime/systime.d
  std/datetime/timezone.d
  std/exception.d
  std/experimental/allocator/building_blocks/allocator_list.d
  std/experimental/allocator/building_blocks/ascending_page_allocator.d
  std/experimental/allocator/building_blocks/region.d
  std/experimental/logger/core.d
  std/file.d
  std/net/curl.d
  std/parallelism.d
  std/path.d
  std/process.d
  std/socket.d
  std/stdio.d
  std/zip.d
Labels: auto-merge

#7417 don't allocate dynamic array when formatting a single character
  std/format.d
Labels: auto-merge

#7418 mark access to `value.store.str` as @trusted
  std/json.d
Labels: auto-merge

#7416 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/bigint-safe.dd
  changelog/isClose.dd
  changelog/mangle_removed.dd
  changelog/remove-stdio-structs.dd
  changelog/remove-string-functions.dd
  changelog/schwartzSort.dd
  changelog/std-functional-curry.dd
  std/bitmanip.d
Labels: Bug Fix, auto-merge

#7413 Add tests for issue 20623 - std.conv.to!string error when argument is an inout float
  std/conv.d
Labels: Bug Fix

#7419 Make sure that uses of testAllocator are inside of StdUnittest version blocks.
  std/experimental/allocator/building_blocks/affix_allocator.d
  std/experimental/allocator/building_blocks/bitmapped_block.d
  std/experimental/allocator/building_blocks/fallback_allocator.d
  std/experimental/allocator/building_blocks/free_tree.d
  std/experimental/allocator/building_blocks/kernighan_ritchie.d
  std/experimental/allocator/building_blocks/quantizer.d
  std/experimental/allocator/building_blocks/region.d
  std/experimental/allocator/building_blocks/scoped_allocator.d
  std/experimental/allocator/gc_allocator.d
  std/experimental/allocator/mallocator.d
Labels: allocators

#7420 add Date.isoWeekYear and Date.fromISOWeek
  changelog/date-isoweek.dd
  std/datetime/date.d
Labels: auto-merge

#7423 std.algorithm.iteration: Fix typo.
  std/algorithm/iteration.d
Labels: auto-merge

#7422 Some followup changes for iOS derived platforms
  std/path.d
  std/random.d
  std/system.d
Labels: auto-merge

#7428 Explicitly show how to read from a file into AA records
  std/csv.d
Labels: auto-merge-squash

#7259 Add @nogc to all relevant unittests in comparison.d
  std/algorithm/comparison.d
Labels: 72h no objection -> merge

#7426 sha.d: assert msg cannot be scope
  std/digest/sha.d
Labels: Blocking Other Work

#7429 typo in docs
  std/datetime/date.d
Labels: Trivial, auto-merge, documentation

#7430 Fix socket test for iOS derived platforms
  std/socket.d
Labels: auto-merge

#6844 Add support for RISC-V 32 & 64 bit
  std/experimental/allocator/building_blocks/region.d
  std/math.d
Labels: auto-merge

#7431 Bump minimum MACOSX version to 10.9
  posix.mak
Labels: auto-merge

#7435 [dmd-cxx] Backport IeeeFlagsSupport and FloatingPointControlSupport
  std/math.d
Labels: Easy Review
