Repository dlang/phobos, pull requests merged in 2021-08, with the labels that each got.

#7506 Fix issue 20665 - std.concurrency.spawn should document not working with delegates
  std/concurrency.d
Labels: 72h no objection -> merge, Enhancement, auto-merge

#8184 [DSSv3] Fix Issue 16218 - Windows std.file.readImpl should be marked @system
  std/file.d
Labels: Enhancement

#7712 Make `std.concurrency.Tid.toString` @safe-able
  std/concurrency.d
Labels: auto-merge

#8176 Fix Issue #22140: FunctionTypeOf fails for template opCall without any templated argument
  std/traits.d
Labels: Bug Fix

#8183 [DSSv3] Fix Issue 16210 - std.utf.byUTF can be made into a bidirectional range
  std/utf.d
Labels: Enhancement

#8187 Fix issue 22176: Revert #7759 "Deprecated Nullable.get warning with Appenders"
  std/typecons.d
Labels: Bug Fix, auto-merge, 72h no objection -> merge

#8189 merge stable
  std/typecons.d
Labels: Bug Fix, auto-merge

#8191 Fix Cirrus CI (bump Ubuntu to 18.04)
  .cirrus.yml
Labels: auto-merge

#8192 Fix issue 22077 - `std.sumtype` support for copy constructors is inco…
  std/sumtype.d
Labels: Bug Fix, auto-merge

#8185 [DSSv3] Fix Issue 19727 - std.algorithm.endsWith fails to compile while startsWith succeeds
  std/algorithm/iteration.d
  std/algorithm/searching.d
  std/path.d
Labels: Bug Fix, Enhancement

#8194 Cirrus CI: Add FreeBSD 11 pipeline
  .cirrus.yml
Labels: auto-merge, Continuous Integration

#8195 Cirrus CI: Bump FreeBSD version to 12.2
  .cirrus.yml
Labels: auto-merge, Continuous Integration

#8197 Fix issue #22222 - Custom unittest runner on phobos fails due to segfault on fork() exiting
  std/stdio.d
Labels: Bug Fix, auto-merge

#8196 std.math.algebraic: use fabs from druntime
  std/math/algebraic.d
Labels: auto-merge

#8201 Fix Issue 22225 - SumType: Some assignments should be able to execute…
  std/sumtype.d
Labels: Enhancement, auto-merge

#8200 define hnsec
  std/datetime/systime.d
Labels: documentation, Trivial

#8208 Fix Issue 22117 - Can't store scope pointer in a SumType
  std/sumtype.d
Labels: Enhancement

#8209 std.random: Add test for Issue 8671
  std/random.d
Labels: auto-merge, Easy Review

#8223 make: remove duplicate ifdef block for NO_AUTODECODE
  posix.mak
Labels: Trivial, auto-merge

#8222 std.exception: make unittests reproducible on -boundscheck=off
  std/exception.d
Labels: auto-merge

#8221 Fix Issue 22249 - std.experimental.checkedint: Warn.onLowerBound does…
  std/experimental/checkedint.d
Labels: Trivial, Bug Fix, auto-merge

#8220 std.range: make unittests reproducible when -boundscheck=off is present
  std/range/package.d
Labels: auto-merge

#8218 Make JSONValue.opBinaryRight!"in" inout
  std/json.d
Labels: Bug Fix, auto-merge, Needs Changelog, needs bugzilla issue

#8040 Use alias assignment in Filter
  std/meta.d
Labels: auto-merge

#8036 Improve ReplaceAll
  std/meta.d
Labels: auto-merge, stalled

#8203 yaml: make files comply with YAML specification
  .cirrus.yml
  .codecov.yml
Labels: auto-merge

#8202 fix issue 20937 - std.range.array of a lengthless range with indirection is not @safe
  std/array.d
Labels: Bug Fix, auto-merge

#8224 Test compiling Phobos with `-boundscheck=off` in CI
  .circleci/run.sh
  posix.mak
Labels: auto-merge
