Repository dlang/phobos, pull requests merged in 2021-05, with the labels that each got.

#8024 Simplify and improve staticIndexOf
  std/meta.d
Labels: auto-merge

#8026 Simplify isSame
  std/meta.d
Labels: auto-merge

#8028 Fix Issue 21512 - RedBlackTree!Tid treats any values as duplicated except for Tid.init
  std/concurrency.d
Labels: Bug Fix, auto-merge

#8027 std.process: Add scope to pipeProcessImpl command parameter
  std/process.d
Labels: auto-merge

#8018 std.format: handle "exotic" reals by casting to double
  changelog/formatting_floats_in_CTFE.dd
  changelog/formatting_some_reals_as_doubles.dd
  std/format/internal/write.d
  std/format/package.d
Labels: auto-merge, std.format

#8023 Sync Fields with FieldNameTuple for interfaces
  changelog/fields_interface.dd
  std/traits.d
Labels: auto-merge-squash

#8032 Workaround for https://issues.dlang.org/show_bug.cgi?id=21889
  std/meta.d
Labels: auto-merge

#8035 container.array: RangeT: moveBack: Improve an assertion.
  std/container/array.d
Labels: auto-merge

#8025 Fix Issues 21728, 21729 and 21730 (check for open file, before using trustedFread)
  std/stdio.d
Labels: Bug Fix

#8041 [dmd-cxx] std.process: Change visibility of searchPathFor to package
  std/process.d
Labels: Easy Review, auto-merge

#8029 Fix Issue 21456 - std.format does not accept enum member with string base type as template parameter
  std/format/package.d
Labels: Bug Fix, auto-merge, std.format

#8042 Again use core.math intrinsics instead of std.math wrappers
  std/complex.d
  std/internal/math/errorfunction.d
  std/math/algebraic.d
  std/math/exponential.d
  std/math/operations.d
  std/math/rounding.d
  std/math/trigonometry.d
Labels: auto-merge

#8020 Fix Issue 21808 - std.format: It should be possible to change the order of key and value of AAs.
  std/format/internal/write.d
  std/format/package.d
Labels: Enhancement, auto-merge, std.format

#8015 std.format: Add formatting integers with %e, %f, %g and %a.
  changelog/add_format_integers_as_floats.dd
  std/format/internal/write.d
  std/format/package.d
  std/format/write.d
  std/uni/package.d
Labels: 72h no objection -> merge, Enhancement, std.format

#8030 Add transition note from approxEqual to isClose.
  std/math/operations.d
Labels: 72h no objection -> merge

#8022 extractBitpattern: Add implied bit to mantissa and subtract bias from exponent.
  std/format/internal/floats.d
  std/math/operations.d
Labels: 72h no objection -> merge, Refactoring, auto-merge, math, std.format

#8051 Issue 19446 - [std.encoding] BOM.utf7 is missing
  std/encoding.d
Labels: Easy Review, auto-merge-squash

#8056 std.format: formatting floating points is meanwhile pure
  std/format/internal/write.d
Labels: Trivial, std.format

#8049 Fix Issue 21900 - std.format: round to even does not work for hex integers with letters
  std/format/internal/write.d
Labels: Bug Fix, std.format

#8058 Remove duplicate assumePureFunction from std.regex
  std/regex/internal/ir.d
  std/regex/package.d
Labels: auto-merge

#8046 Make staticIsSorted use static foreach instead of recursion
  std/meta.d
Labels: auto-merge

#8063 Fix missing space in exception text in std.conv.to
  std/conv.d
Labels: auto-merge

#8064 std.math.algebraic: Support more float types in hypot
  std/math/algebraic.d
Labels: auto-merge, math

#8065 std.math.algebraic: Convert hypot to a template
  std/math/algebraic.d
Labels: auto-merge, math

#8067 std.complex: Add missing imports in unittests for non-DigitalMars targets
  std/complex.d
Labels: Trivial, math

#8055 Fix Issue 9489 - writeln of struct with disabled copy ctor
  std/format/internal/write.d
  std/format/write.d
  std/stdio.d
Labels: Bug Fix, auto-merge, std.format

#8069 merge stable
  std/process.d
  std/stdio.d
Labels: Bug Fix, auto-merge

#8070 Fix Issue 21916 - Error message is obfuscated when using wrong format…
  std/format/package.d
Labels: Bug Fix, auto-merge

#8059 std.format: Use rounding tool to round %a on floats.
  std/format/internal/floats.d
  std/format/internal/write.d
Labels: 72h no objection -> merge, std.format

#8050 std.format: Use rounding tool to round %e on floats.
  std/format/internal/floats.d
Labels: 72h no objection -> merge, std.format

#8074 Cleanup temp files in libphobos unittest at src/std/process.d
  std/process.d
Labels: auto-merge

#8075 Cleanup temp files in std.process and std.experimental.checkedint
  std/experimental/checkedint.d
  std/process.d
Labels: auto-merge

#8078 Fix Issue 21125 - Typo in std.range.refRange documentation for opIndex
  std/range/package.d
Labels: Bug Fix, Easy Review, Trivial, auto-merge

#8086 Annotate allocator/common.d to please dlang/dmd#12520
  std/experimental/allocator/common.d
Labels: auto-merge

#8099 Annotate std/xml.d to please dlang/dmd#12520
  std/xml.d
Labels: auto-merge

#8098 Annotate std/utf.d to please dlang/dmd#12520
  std/utf.d
Labels: auto-merge

#8097 Annotate std/uni/package.d to please dlang/dmd#12520
  std/uni/package.d
Labels: auto-merge

#8096 Annotate std/string.d to please dlang/dmd#12520
  std/string.d
Labels: auto-merge

#8095 Annotate std/stdio.d to please dlang/dmd#12520
  std/stdio.d
Labels: auto-merge

#8094 Annotate std/socket.d to please dlang/dmd#12520
  std/socket.d
Labels: auto-merge

#8087 Annotate sha_SSSE3.d to please dlang/dmd#12520
  std/internal/digest/sha_SSSE3.d
Labels: auto-merge

#8079 Annotate std/algorithm/searching.d to please dlang/dmd#12520
  std/algorithm/searching.d
Labels: auto-merge

#8089 Annotate std/net/isemail.d to please dlang/dmd#12520
  std/net/isemail.d
Labels: auto-merge

#8084 Annotate bitmapped_block.d to please dlang/dmd#12520
  std/experimental/allocator/building_blocks/bitmapped_block.d
Labels: auto-merge

#8083 Annotate std/container/dlist.d to please dlang/dmd#12520
  std/container/dlist.d
Labels: auto-merge

#8080 Annotate std/base64.d to please dlang/dmd#12520
  std/base64.d
Labels: auto-merge

#8082 Annotate std/bitmanip to please dlang/dmd#12520
  std/bitmanip.d
Labels: auto-merge

#8102 std.traits: Fix unittest for isNumeric
  std/traits.d
Labels: auto-merge

#8103 Revert "Annotate std/path.d to please dlang/dmd#12520"
  std/path.d
Labels: auto-merge

#8092 Revert "Fix Issue 9489 - writeln of struct with disabled copy ctor"
  std/format/internal/write.d
  std/format/write.d
  std/stdio.d
Labels: Bug Fix, auto-merge

#8093 Annotate std/range/package.d to please dlang/dmd#12520
  std/range/package.d
Labels: auto-merge

#8106 Annotate std/path.d to please dlang/dmd#12520, absolutePath excluded
  std/path.d
Labels: auto-merge

#8077 Fix issue 21926 - Allow leadings zeros in std.conv.octal(string)
  std/conv.d
Labels: Enhancement, auto-merge

#8073 std.format: Use rounding tool to round %f on floats.
  std/format/internal/floats.d
Labels: 72h no objection -> merge

#8085 Annotate std/file.d to please dlang/dmd#12520
  std/file.d
  std/path.d
Labels: auto-merge

#8109 add `scope` to parameters of `toUTF32` and `toUTFImpl`
  std/utf.d
Labels: auto-merge

#8066 improve documentation of SortedRange.release
  std/range/package.d
Labels: Bug Fix, auto-merge

#8048 Add missing SharedConstInoutOf and refactor QualifierOf
  std/traits.d
  std/variant.d
Labels: auto-merge

#8118 [stable] Fix missing imports for non-x87 real after std.math split-up
  std/math/exponential.d
  std/math/hardware.d
  std/math/operations.d
  std/math/rounding.d
  std/math/traits.d
Labels: auto-merge

#8112 merge stable
  changelog/formatting_floats_nogc.dd
  std/format/internal/write.d
Labels: auto-merge

#8117 Add `return scope` to xml.toType
  std/xml.d
Labels: auto-merge

#8114 Annotate more return/scope on bigint functions
  std/bigint.d
  std/internal/math/biguintcore.d
Labels: auto-merge

#8115 Use splitter instead of split in getopt
  std/getopt.d
Labels: auto-merge

#8119 add @trusted for scope pointer to scope pointer
  std/process.d
Labels: Blocking Other Work, auto-merge
