Repository dlang/phobos, pull requests merged in 2021-06, with the labels that each got.

#8121 Use `icmp` instead of `toUpper` in getopt
  std/getopt.d
Labels: auto-merge

#8122 Add `return scope` to std.uni MultiArray ctor
  std/uni/package.d
Labels: auto-merge

#8125 Fix local variable lifetimes in systime parsing
  std/datetime/systime.d
Labels: auto-merge

#8128 [stable] std.math.exponential: Minimally relax a pow() unittest for targets with 64-bit real
  std/math/exponential.d
Labels: auto-merge

#8129 [stable] std.format.internal.floats: Restore compilability of unittests for targets with quadruple `real` precision
  std/format/internal/floats.d
Labels: auto-merge

#8131 [stable] std.stdio: Restore compilability of unittests for iOS
  std/stdio.d
Labels: auto-merge

#8132 merge stable
  changelog/add_centering_flag.dd
  changelog/add_conversion_target.dd
  changelog/add_format_integers_as_floats.dd
  changelog/bugfix_for_pow.dd
  changelog/deprecate_enforceValidFormatSpec.dd
  changelog/deprecate_formatElement.dd
  changelog/deprecate_unformatElement.dd
  changelog/fieldnametuple_interface.dd
  changelog/fields_interface.dd
  changelog/formatting_floats_in_CTFE.dd
  changelog/formatting_floats_nogc.dd
  changelog/formatting_some_reals_as_doubles.dd
  changelog/nullable-remove-alias-get-this.dd
  changelog/rework_format_docs.dd
  changelog/splitting_format.dd
  changelog/splitting_math.dd
  changelog/splitwhen.dd
  changelog/std-datetime.dd
  changelog/std-exception.dd
  changelog/std-sumtype.dd
  changelog/transposed-remove-save.dd
  std/format/internal/floats.d
  std/math/exponential.d
  std/math/hardware.d
  std/math/operations.d
  std/math/rounding.d
  std/math/traits.d
  std/stdio.d
Labels: auto-merge

#8127 [stable] std.math.operations: Slightly revise extractBitpattern()
  std/math/operations.d
Labels: auto-merge

#8133 std.conv: Avoid undefined bytes in toChars() results for radix 10
  std/conv.d
Labels: Bug Fix

#8130 Fix std.algorithm findSplit methods module documentation
  std/algorithm/searching.d
Labels: documentation

#8116 Add `return scope` to realloc
  std/internal/cstring.d
  std/internal/memory.d
  std/uni/package.d
Labels: auto-merge

#8123 Use `static foreach` for correct `scope` inference
  std/conv.d
  std/range/package.d
Labels: auto-merge

#7741 declaring templates inside static foreach is not reliable
  std/math/hardware.d
Labels: auto-merge

#8138 Fix std json static assert
  std/json.d
Labels: auto-merge

#8142 [dmd-cxx] Simplify some Proxy.opDispatch conditions
  std/typecons.d
Labels: Easy Review, auto-merge

#8143 std.container.Array: Simplify implementation of length (by calling reserve).
  std/container/array.d
Labels: auto-merge

#8144 Fix Issue 20393 - formattedRead accepts input, that should be rejected
  std/format/read.d
  std/format/spec.d
Labels: Bug Fix

#8120 file: document dirEntries as no garantee of sorted output
  std/file.d
Labels: auto-merge

#8148 Improve memory usage & speed of std.traits.isIntegral & isSomeChar
  std/traits.d
Labels: auto-merge

#8149 Streamline std.traits.BuiltinTypeOf & IntegralTypeOf
  std/traits.d
Labels: auto-merge

#8147 [Reg 2.074] std.traits.isFloatingPoint, isNumeric, isUnsigned, and isSigned should never be true for SIMD vectors, imaginary/complex numbers, or enums with character base types
  std/traits.d
Labels: Bug Fix, stable-stalled

#8152 [stable] [Reg 2.097] std.typecons.RefCounted!T for struct T without an explicit toString or alias this previously could be converted to string even when uninitialized but now cannot
  std/typecons.d
Labels: Bug Fix, auto-merge
