Repository dlang/phobos, pull requests merged in 2021-09, with the labels that each got.

#8229 Use version (StdUnittest) in std/meta.d
  std/meta.d
Labels: auto-merge

#8227 Make alias templates to core.internal.traits symbolic aliases to avoid extra te…
  std/traits.d
Labels: auto-merge-squash

#8226 Remove need for Unqual in EndianSwapper
  std/bitmanip.d
Labels: auto-merge

#8233 Remove unused and inaccessible std.iteration.algorithm.aggregate(...)
  std/algorithm/iteration.d
Labels: auto-merge

#8238 Fix Issue 22297 - Behavior of minElement and maxElement with empty ra…
  std/algorithm/searching.d
Labels: documentation, Bug Fix, auto-merge

#7350 add some more auth types to etc.c.curl
  etc/c/curl.d
Labels: auto-merge-squash

#7467 Only use 'from' if a packet was actually received
  std/socket.d
Labels: Bug Fix, auto-merge, 72h no objection -> merge

#8236 merge stable
  std/array.d
Labels: Bug Fix, auto-merge

#8240 Completed attribute lithany on `sameTail` and `sameHead`
  std/array.d
Labels: auto-merge

#7148 Alias traits from druntime
  std/traits.d
Labels: auto-merge-squash

#8228 Replace template AliasThisTypeOf with inlined calls to __traits
  std/traits.d
Labels: auto-merge

#8241 Temporarily comment one test in traits to be able to graciously fix druntime implementation
  std/traits.d
Labels: Blocking Other Work, auto-merge

#8242 Re-add std.traits.Fields test with interface
  std/traits.d
Labels: auto-merge

#8243 std.typecons: Minimize redundant template declarations/instantiations wrt. Tuple
  std/typecons.d
Labels: auto-merge

#8244 std.algorithm.sorting: fix typo and related texts
  std/algorithm/sorting.d
  std/string.d
Labels: auto-merge

#8248 Fix Issue 22325 - ReplaceType fails on templated type instantiated wi…
  std/typecons.d
Labels: Bug Fix, auto-merge

#8246 Fix issue 20554 - std.algorithm.searching.all 's static assert produc…
  std/algorithm/searching.d
Labels: Bug Fix, Enhancement

#8249 Draft: Qualify some function parameters under std.format as const to reduce template bloat
  std/format/internal/floats.d
  std/format/internal/write.d
  std/math/operations.d
Labels: auto-merge

#8254 Mentions type in error message for missing opPostMove
  std/algorithm/mutation.d
Labels: auto-merge

#7444 Fix Issue 22340 - totalCPUs may not return accurate number of CPUs
  std/parallelism.d
Labels: Enhancement, auto-merge, needs bugzilla issue

#6858 add -preview=fieldwise to build
  posix.mak
  win32.mak
  win64.mak
Labels: Enhancement, stalled, auto-merge-squash

#8255 Fix issue 21507 - added precision for function SysTime.toIsoExtString
  std/datetime/systime.d
Labels: Enhancement, auto-merge-squash
