Repository dlang/phobos, pull requests merged in 2021-12, with the labels that each got.

#8325 Fix Issue 22557 - std.traits.fqnType is missing support for typeof(null)
  std/traits.d
Labels: Bug Fix, Enhancement, auto-merge

#8326 Fix issue 22561: Allow joiner to reassign range values that contain immutable fields.
  std/algorithm/iteration.d
Labels: Bug Fix

#8329 schwartzSort to use pureMalloc so it's more pure
  std/algorithm/sorting.d
Labels: auto-merge

#8330 Issue 22582 - [std.algorithm.count] predicate does not implicitly convert to bool
  std/algorithm/searching.d
Labels: Bug Fix, auto-merge-squash

#8331 Fix a potential memory leak, typos
  std/parallelism.d
Labels: auto-merge

#8332 merge stable
  std/traits.d
Labels: Bug Fix, Enhancement, auto-merge

#8333 Ignore SECURITY file when listing timezones
  std/datetime/timezone.d
Labels: auto-merge

#8334 zlib: Synchronize testsuite with 1.2.11
  etc/c/zlib/doc/algorithm.txt
  etc/c/zlib/linux.mak
  etc/c/zlib/osx.mak
  etc/c/zlib/test/example.c
  etc/c/zlib/test/infcover.c
  etc/c/zlib/test/minigzip.c
  etc/c/zlib/win32.mak
  etc/c/zlib/win64.mak
  win32.mak
  win64.mak
Labels: coverage, auto-merge, Build System

#8337 Fix typecons Proxy.opCmp
  std/typecons.d
Labels: auto-merge

#8338 Fix issue 22608 - RandomAccessInfinite is not a valid random-access range
  std/range/interfaces.d
Labels: Bug Fix, auto-merge

#8339 Add unittest for issue 22609
  std/format/write.d
Labels: auto-merge

#8340 sumtype: remove redundant "See Also" in tryMatch documentation
  std/sumtype.d
Labels: auto-merge

#8214 Make `throw` functions compile with dip1000 pure-scope fix
  std/conv.d
  std/utf.d
  std/xml.d
Labels: WIP

#8343 Fix link in documentation
  std/algorithm/mutation.d
Labels: auto-merge

#8344 Fix Issue 22105 - std.container.array.Array.length setter creates val…
  std/algorithm/mutation.d
  std/container/array.d
Labels: Bug Fix, auto-merge

#8345 Fix Issue 18051 - missing enum support in formattedRead/unformatValue
  std/format/internal/read.d
  std/format/read.d
Labels: Enhancement, auto-merge

#8348 Azure: Replace deprecated vs2017-win2016 image with windows-2019
  azure-pipelines.yml
Labels: auto-merge, Continuous Integration
