Repository dlang/phobos, pull requests merged in 2021-11, with the labels that each got.

#8311 Fix 22488 - Add inout to allow Array.data for const/immutable Array's
  std/container/array.d
Labels: Enhancement, auto-merge

#8310 Fix 22487 - Don't access payload for unititialized array data
  std/container/array.d
Labels: Bug Fix, auto-merge

#8312 [stable] cirrus: Switch to big-sur image
  .cirrus.yml
Labels: auto-merge, Continuous Integration

#8313 Merge `stable` in `mater`
  .circleci/run.sh
  .cirrus.yml
  std/container/array.d
  std/datetime/timezone.d
  std/math/algebraic.d
  std/parallelism.d
  std/system.d
Labels: Bug Fix, Enhancement, auto-merge, stable -> master, Continuous Integration

#8316 Fix Issue 22511 - Add explicit copy ctor for Nullable
  std/typecons.d
Labels: Enhancement

#8318 Merge PR #8315 & #8316 in to `stable`
  std/container/dlist.d
  std/typecons.d
Labels: Bug Fix, Enhancement, auto-merge

#8319 Add explicit `return` to `inout` functions
  std/file.d
  std/internal/cstring.d
  std/json.d
  std/process.d
  std/stdio.d
  std/uni/package.d
Labels: auto-merge

#8321 Prefer __traits(initSymbol) over TypeInfo.initializer()
  std/algorithm/mutation.d
Labels: auto-merge

#8320 Fix `scope` usage of SysTime/TimeZone
  std/datetime/interval.d
  std/datetime/systime.d
  std/datetime/timezone.d
  std/file.d
  std/typecons.d
Labels: auto-merge

#8324 std.random: Fix test for version(X32) targets
  std/random.d
Labels: Bug Fix, auto-merge
