Repository dlang/phobos, pull requests merged in 2022-02, with the labels that each got.

#8374 win32.mak: Explicitly use 32omf instead of $(MODEL)
  win32.mak
Labels: auto-merge, Build System

#8373 Fix Issue 22738 - std.file.tempDir adds an addition / even when it already has one
  std/file.d
Labels: Bug Fix

#8377 Fix Issue 22572 - Cannot define SumType over immutable struct with Nu…
  std/sumtype.d
Labels: Bug Fix, auto-merge

#8378 Merge branch 'stable' into merge_stable
  std/typecons.d
Labels: auto-merge

#8379 Fix issue 22771 - BigInt divMod can return "-0" (negative zero)
  std/bigint.d
Labels: Bug Fix, auto-merge

#8382 Fix SysTime.fromXXXString() documentation errors.
  std/datetime/systime.d
Labels: auto-merge

#8380 etc.c.odbc: Update removal dates for ODBC deprecations
  etc/c/odbc/sql.d
  etc/c/odbc/sqlext.d
  etc/c/odbc/sqltypes.d
  etc/c/odbc/sqlucode.d
Labels: Trivial, auto-merge, Deprecation

#8381 std.zip: Remove declarations with expired deprecations
  std/zip.d
Labels: auto-merge, Easy Review, Deprecation

#8384 Make std.uni unittest compile with inout-return fix
  std/uni/package.d
Labels: auto-merge

#8383 Fix return/inout usage in rbtree
  std/container/rbtree.d
Labels: auto-merge

#8385 Unblock "address of ref can be assigned to non-scope parameter"
  std/bigint.d
  std/file.d
  std/internal/math/biguintcore.d
Labels: auto-merge

#8387 Fix bigint `return scope` order
  std/bigint.d
Labels: auto-merge

#8388 fix Issue 22791 - std\socket.d(790) Heisenbug random failure
  std/socket.d
Labels: Enhancement

#8391 ci: use ci/run.sh and ci/cirrusci.sh scripts from dmd
  .cirrus.yml
Labels: auto-merge

#8392 sumtype: add example of memory corruption to docs
  std/sumtype.d
Labels: auto-merge

#8390 getopt: mark defaultGetoptPrinter as @safe
  std/getopt.d
Labels: Enhancement

#8394 sumtype: work around issue 21975 in isSumType
  std/sumtype.d
Labels: auto-merge

#8395 std/file: use size_t instead of ulong for ReadFile on Windows
  std/file.d
Labels: auto-merge

#8393 Fix Issue 18036 - Documentation of moveFront()
  std/range/primitives.d
Labels: documentation, Bug Fix, auto-merge
