Repository dlang/phobos, pull requests merged in 2022-12, with the labels that each got.

#8634 remove isScalar check from std.traits.isPointer
  std/traits.d
Labels: auto-merge, Easy Review, Refactoring

#8641 replace isImplicitlyConvertible with is expression
  std/array.d
  std/concurrency.d
  std/conv.d
  std/traits.d
  std/typecons.d
Labels: Easy Review, Refactoring

#8640 remove unused reference to isPointer from std.stdio
  std/stdio.d
Labels: Easy Review, Refactoring

#8636 remove use of isPointer from std.array
  std/array.d
Labels: Easy Review, Refactoring

#8635 remove isPointer use in std.utf
  std/utf.d
Labels: Easy Review, Refactoring

#8639 remove use of isPointer from std.getopt
  std/getopt.d
Labels: auto-merge, Easy Review, Refactoring

#8633 [stable] Fix Issue 22745 - std.parallelism.parallel fails to process empty range on a single CPU
  std/parallelism.d
Labels: Bug Fix

#8638 remove use of isPointer from std.exception
  std/exception.d
Labels: auto-merge, Easy Review, Refactoring

#8637 remove use of isPointer from std.traits
  std/traits.d
Labels: auto-merge, Easy Review, Refactoring

#8642 std.math.hardware: Fix broken IEEE FP flags tests
  std/math/hardware.d
Labels: auto-merge

#8643 std.math.hardware: Use forceOp in another ieeeFlags test
  std/math/hardware.d
Labels: math, auto-merge

#8644 Fix Issue 23319 - std.range.Generator does not work with non-mutable elements
  std/range/package.d
Labels: Bug Fix, auto-merge

#8645 Fix typo in doc for std.algorithm.mutation.fill
  std/algorithm/mutation.d
Labels: Trivial, auto-merge

#8646 Clarify that .uniq by default expects a sorted range.
  std/algorithm/iteration.d
Labels: auto-merge

#8649 std.random: Fix unittests on x32 ABI targets
  std/random.d
Labels: auto-merge, Easy Review

#8499 std.math.exponential: Implement log/log2/log10 for double- and float-precision
  changelog/log_float_double_implementations.dd
  std/math/exponential.d
  std/math/operations.d
  std/numeric.d
  std/parallelism.d
Labels: math, auto-merge

#8650 merge stable
  std/parallelism.d
Labels: Bug Fix, auto-merge, stable -> master

#8617 Upstream the Unicode database table generator and update the tables to 15
  .dscanner.ini
  CODEOWNERS
  changelog/unicode_table_generator.dd
  std/internal/unicode_comp.d
  std/internal/unicode_decomp.d
  std/internal/unicode_grapheme.d
  std/internal/unicode_norm.d
  std/internal/unicode_tables.d
  std/uni/package.d
  tools/unicode_table_generator.d
Labels: 72h no objection -> merge

#8652 Fix issue 23540 - std.uni loadProperty aliases for C are incorrect
  changelog/unicode_properties_c.dd
  std/uni/package.d
Labels: Bug Fix

#8651 Fix Issue 23561 - std.typecons.Unique!struct does not destroy struct …
  std/typecons.d
Labels: Bug Fix, auto-merge-squash

#8653 [trivial] Tweak a few tests
  std/conv.d
  std/typecons.d
Labels: Trivial, auto-merge

#8655 Typo: begining -> beginning
  std/regex/package.d
Labels: Trivial, auto-merge

#8654 Add changelog for Unique!struct calling destroy
  changelog/unique-struct-dtor.dd
Labels: auto-merge
