Repository dlang/phobos, pull requests merged in 2022-06, with the labels that each got.

#8470 nogc biguintx86.d
  std/internal/math/biguintx86.d
Labels: auto-merge

#8474 Fix Issue 23182 - Can't assign struct with opAssign to SumType in CTFE
  std/sumtype.d
Labels: Bug Fix, auto-merge

#8473 remove compile features from std.experimental.logger
  changelog/logger_remove_compile_time_loglevel.dd
  std/experimental/logger/core.d
  std/experimental/logger/package.d
Labels: auto-merge

#8475 Issue 23190 - make some std.file unittests `@safe`
  std/file.d
Labels: auto-merge

#8479 Extend floating point precision in some tests
  std/complex.d
  std/math/algebraic.d
  std/math/trigonometry.d
Labels: auto-merge

#8477 RISCV: Fix wrong ExceptionMask values
  std/math/hardware.d
Labels: auto-merge

#8467 Fix 23132 - Avoid ranges copy when compared for equality
  std/algorithm/comparison.d
Labels: Bug Fix, Enhancement, auto-merge, stable-stalled

#8481 Add missing `return scope` to std.file
  std/file.d
Labels: Blocking Other Work, DIP25 / DIP1000, auto-merge

#8480 preallocate oom error
  std/stdio.d
Labels: Bug Fix

#8483 fix Issue 23215: segfault in std.file.remove
  std/file.d
Labels: Bug Fix
