Repository dlang/phobos, pull requests merged in 2022-09, with the labels that each got.

#8551 std.socket: add scope to close
  std/socket.d
Labels: auto-merge

#8553 std.logger 32 bit unittest race condition fix
  std/logger/core.d
Labels: auto-merge

#8556 Fix issue 23324 - Incorrect source link in std.format docs
  std/format/package.d
Labels: documentation, Trivial, auto-merge

#8557 std.logger.core unittest forgotton thread.join
  std/logger/core.d
Labels: auto-merge

#8563 merge stable
  std/typecons.d
Labels: Bug Fix, auto-merge

#8564 Fix Stupid -> Snazzy based on updated name.
  std/compiler.d
Labels: auto-merge

#8565 std.conv.octal: simplify implementation
  std/conv.d
Labels: Refactoring

#8567 Fix issue 23333: Make DList range access @nogc
  std/container/dlist.d
Labels: Enhancement, auto-merge

#8572 fix Issue 23340 - std.path: expandTilde erroneously raises onOutOfMemory on failed getpwam_r()
  std/path.d
Labels: Bug Fix, auto-merge

#8571 partial fix for Issue 23344 - std.stdio: error: undefined identifier fputc_unlocked
  std/stdio.d
Labels: Bug Fix, auto-merge, Easy Review

#8575 chore(stdio): annotate postblit of File struct
  std/stdio.d
Labels: auto-merge

#8578 Fix 'the the' typos in Phobos documentation
  std/datetime/stopwatch.d
  std/file.d
  std/internal/math/gammafunction.d
  std/logger/core.d
  std/net/curl.d
  std/uni/package.d
Labels: documentation, Trivial, auto-merge, Easy Review

#8579 Fix Issue 23350 - Nondeterministic test failure in std.concurrency
  std/concurrency.d
Labels: auto-merge

#8582 Fix `@system` annotation in multisort unittest
  std/algorithm/sorting.d
Labels: Blocking Other Work

#8570 Fix issue 14543: std.algorithm.searching.until does n…
  std/algorithm/searching.d
Labels: Bug Fix
