Repository dlang/phobos, pull requests merged in 2022-08, with the labels that each got.

#8522 wrong example - the paren char args are required
  std/algorithm/searching.d
Labels: auto-merge

#8524 std.bigint: toHex pure attrib missed
  std/bigint.d
Labels: auto-merge

#8527 posix.mak: Don't link pthread and libmath on MacOS
  posix.mak
Labels: auto-merge

#8530 replace delegate with simple nested function
  std/json.d
Labels: Blocking Other Work, auto-merge

#8532 getopt: make unittest @system because of delegate
  std/getopt.d
Labels: Blocking Other Work, auto-merge

#8531 [std/regex] Improve docs
  std/regex/package.d
Labels: auto-merge

#8526 fix issue 23140
  std/container/array.d
Labels: Bug Fix, auto-merge, Regression

#8533 get std.typecons to compile with PR #14364
  std/typecons.d
Labels: Blocking Other Work, auto-merge

#8534 make nested class & struct static
  std/array.d
Labels: Blocking Other Work, auto-merge

#8415 std.complex: Add member function to returnComplex as a native type
  std/complex.d
Labels: math, Easy Review, Atila Neves

#8536 more static class in std.array
  std/array.d
Labels: Blocking Other Work

#8535 Switch to faster version of staticMap
  std/meta.d
Labels: Atila Neves

#8538 std.random unittest class should be static
  std/random.d
Labels: Blocking Other Work, auto-merge

#8541 iteration: use static class
  std/algorithm/iteration.d
Labels: Blocking Other Work

#8543 Fix issue 23298 - std.string wrap wraps early
  std/string.d
Labels: Enhancement

#8547 std.path.globMatch: Don't throw from nothrow contract
  std/path.d
Labels: auto-merge

#8546 Remove std.xml, std.digest.digest, and all references to those deprecated modules
  .dscanner.ini
  CODEOWNERS
  changelog/remove-std-digest-digest.dd
  changelog/remove-std-xml.dd
  index.dd
  posix.mak
  std/datetime/timezone.d
  std/digest/crc.d
  std/digest/digest.d
  std/xml.d
  win32.mak
  win64.mak
Labels: auto-merge, Easy Review, Deprecation

#8545 Fix issue 23238 - Cannot write a const Nullable(T, T nullValue)
  std/typecons.d
Labels: Bug Fix

#8548 merge stable
  std/container/array.d
Labels: auto-merge

#8549 [trivial] std.utf.byCodeUnit: Fix typo in documentation
  std/utf.d
Labels: Trivial, auto-merge

#8544 Fix Issue 23268 - clamp no longer accepts shorts
  std/algorithm/comparison.d
Labels: Bug Fix, auto-merge
