Repository dlang/phobos, pull requests merged in 2022-03, with the labels that each got.

#8396 merge stable
  std/datetime/systime.d
Labels: auto-merge

#8397 Revert "sumtype: work around issue 21975 in isSumType"
  std/sumtype.d
Labels: auto-merge

#8402 Disable large allocation test that is not supported by AddressSanitizer
  std/experimental/allocator/mallocator.d
Labels: auto-merge

#8401 Fix 22838 - BitArray.count reads beyond data
  std/bitmanip.d
Labels: Bug Fix

#8403 Fix 22851 - Add source reference to std.sumtype
  std/sumtype.d
Labels: Bug Fix, auto-merge

#8404 merge stable
  changelog/checkedint.dd
  changelog/chunkBy_mostly_safe.dd
  changelog/csv_un_equal_separator_count.dd
  changelog/logger_default_warning.dd
  changelog/support_for_tuples.dd
  std/bitmanip.d
Labels: Bug Fix, auto-merge

#8405 Fix `return scope` in cartesianProduct Result.save
  std/algorithm/setops.d
Labels: auto-merge

#8408 fix issue 22867 - std.utf.decode changes offset despite error.
  std/utf.d
Labels: Bug Fix

#8410 Increase @safety of std.conv
  std/conv.d
Labels: Blocking Other Work, Easy Review, Refactoring, auto-merge-squash

#8411 Fix typo 'preforming'
  std/uni/package.d
Labels: Trivial, Easy Review

#8413 Fix issue 22901 - Can't construct inout SumType
  std/sumtype.d
  std/traits.d
Labels: Bug Fix, auto-merge

#8414 Fixed negation of `BitFlags`
  std/typecons.d
Labels: auto-merge

#8409 Fix issue 22873 - Wrong std.format output for `inout`
  std/format/internal/write.d
Labels: Bug Fix, auto-merge-squash

#8416 Fix incorrect `return scope` annotations
  std/datetime/systime.d
  std/json.d
Labels: DIP25 / DIP1000, auto-merge

#8419 [Refactor] Move toCtString to std.conv
  std/conv.d
  std/functional.d
  std/sumtype.d
Labels: auto-merge, Easy Review, Refactoring

#8418 Make `toLower` and `toUpper` `return scope`
  std/uni/package.d
Labels: DIP25 / DIP1000

#8417 Fix Issue 18374 - Add range functions to Nullable
  changelog/std_typecons_nullable_range.dd
  std/typecons.d
Labels: auto-merge

#8421 Fix 22946 - Mark WindowsException ctor as nothrow
  std/windows/syserror.d
Labels: Bug Fix, auto-merge

#8420 Fix 13541 - Replace plain usages of sysErrorString for errors
  std/file.d
  std/process.d
  std/socket.d
  std/stdio.d
  std/windows/charset.d
  std/windows/syserror.d
Labels: Bug Fix, auto-merge

#8423 Improve `std.conv.parse` support for `scope` strings
  std/conv.d
Labels: DIP25 / DIP1000, auto-merge

#8424 Fix issue 22939 - bad error message: Error: no property `msg` for typ…
  std/format/package.d
  std/format/read.d
  std/format/write.d
  std/outbuffer.d
  std/stdio.d
Labels: Bug Fix, auto-merge

#8422 Fix 22947 - Use wenforce in sysErrorString
  std/windows/syserror.d
Labels: Bug Fix
