Repository dlang/phobos, pull requests merged in 2022-04, with the labels that each got.

#8425 merge stable
  changelog/log_default_info.dd
  std/experimental/logger/core.d
  std/experimental/logger/filelogger.d
  std/experimental/logger/multilogger.d
  std/format/package.d
  std/format/read.d
  std/format/write.d
  std/outbuffer.d
  std/stdio.d
Labels: Bug Fix, auto-merge

#8427 merge stable
  changelog/log_default_info.dd
Labels: auto-merge

#8428 Fix Issue 22998 - Update to zlib 1.2.12
  etc/c/zlib.d
  etc/c/zlib/ChangeLog
  etc/c/zlib/README
  etc/c/zlib/crc32.c
  etc/c/zlib/crc32.h
  etc/c/zlib/deflate.c
  etc/c/zlib/deflate.h
  etc/c/zlib/gzguts.h
  etc/c/zlib/gzlib.c
  etc/c/zlib/gzread.c
  etc/c/zlib/gzwrite.c
  etc/c/zlib/infback.c
  etc/c/zlib/inffast.c
  etc/c/zlib/inflate.c
  etc/c/zlib/inflate.h
  etc/c/zlib/inftrees.c
  etc/c/zlib/test/example.c
  etc/c/zlib/trees.c
  etc/c/zlib/zlib.3
  etc/c/zlib/zlib.h
  etc/c/zlib/zutil.c
  etc/c/zlib/zutil.h
Labels: Bug Fix

#8429 Fix switch fallthrough in std.regex
  std/regex/internal/parser.d
Labels: auto-merge

#8430 Fix issue 22213 - Base64: Missing `@nogc` attribute on encodeLength
  std/base64.d
Labels: Bug Fix

#8431 Fix std.path unittest returning dangling pointer
  std/path.d
Labels: Blocking Other Work, DIP25 / DIP1000

#8426 add std.int128 a 128 bit integer arithmetic type
  .dscanner.ini
  posix.mak
  std/int128.d
  win32.mak
  win64.mak
Labels: Enhancement, 72h no objection -> merge

#8433 Fix Issue 20182 - [REG 2.086.0] std.traits.ParameterDefaults fails for copy constructor of nested struct
  std/traits.d
Labels: Bug Fix, auto-merge

#8435 Fix: add missing FunctionAttribute
  std/traits.d
  std/typecons.d
Labels: auto-merge

#8440 Issue 22986: Mark ErrnoException.errno as scope
  std/exception.d
Labels: Bug Fix, DIP25 / DIP1000, auto-merge

#8448 Add changelog entry for zlib update
  changelog/zlib.dd
Labels: auto-merge
