Repository dlang/phobos, pull requests merged in 2022-07, with the labels that each got.

#8491 posix.mak: Pass absolute path of dmd when invoking druntime's makefile
  posix.mak
Labels: auto-merge, Easy Review, Build System

#8488 compile Phobos .c files with ImportC for win32omf
  win32.mak
Labels: Easy Review, ImportC

#8490 compile Phobos .c files with ImportC for mscoff
  win64.mak
Labels: auto-merge, Easy Review, ImportC

#8493 std.math.exponential: Implement pure logb() for double and float precision
  std/math/exponential.d
Labels: math, auto-merge

#8494 std.math.exponential: Split generic logN implementations to own impl templates
  std/math/exponential.d
Labels: math

#8485 upgrade zlib C files to C11
  etc/c/zlib/gzguts.h
  posix.mak
Labels: Easy Review, auto-merge-squash

#8496 std.math.exponential: Fix coefficients for log2 and log10
  std/math/exponential.d
Labels: math, Blocking Other Work, auto-merge

#8498 std.complex: Use complex(LN10) as divisor in log10
  std/complex.d
Labels: math, Blocking Other Work, auto-merge, Easy Review

#8501 std.sumtype: Move TagTuple to module level to reduce instantiations
  std/sumtype.d
Labels: auto-merge

#8500 Use try-catch instead of scope(failure) for block that returns
  std/typecons.d
Labels: Blocking Other Work

#8495 Fix Issue 18631 - std.random.choice does not work with const arrays
  std/random.d
Labels: Bug Fix, auto-merge

#8503 merge stable
  std/algorithm/comparison.d
  std/typecons.d
Labels: Bug Fix, auto-merge

#8506 std.math: Faster floor(double) implementation
  std/math/package.d
  std/math/rounding.d
Labels: math, auto-merge

#8508 [stable] cirrus.yml: Use an alternative mirror for FreeBSD 11
  .cirrus.yml
Labels: auto-merge

#8507 Fix 23245, 23246 - std.format regressions
  std/format/internal/write.d
  std/format/package.d
Labels: Bug Fix, Enhancement, auto-merge

#8512 Trivial: Remove Jenkinsfile
  Jenkinsfile
Labels: auto-merge

#8511 etc.c.curl: Remove a usage of 'in' with scope
  etc/c/curl.d
Labels: auto-merge

#8516 Fix issue 18735 all versions of find and canfind should identify usag…
  std/algorithm/searching.d
Labels: Enhancement, auto-merge

#8489 sharedLog returning shared(Logger)
  changelog/logger_sharedLog_returning_shared_logger.dd
  std/experimental/logger/core.d
  std/experimental/logger/filelogger.d
  std/experimental/logger/multilogger.d
Labels: Bug Fix, 72h no objection -> merge

#8517 Fix Issue 13893 - rawRead must take a non-empty buffer
  std/stdio.d
Labels: Enhancement

#8518 documentation / repair broken link for std.checkedint
  std/experimental/checkedint.d
Labels: documentation, auto-merge

#8514 std.algorithm: improve documentation of filter
  std/algorithm/iteration.d
Labels: documentation, auto-merge-squash

#8519 Fix 23270 - std.random.dice is poorly documented
  std/random.d
Labels: documentation, Bug Fix

#8520 Add std.internal.memory to the makefiles
  posix.mak
  win32.mak
  win64.mak
Labels: auto-merge
