Repository dlang/phobos, pull requests merged in 2022-01, with the labels that each got.

#8351 Fix Issue 22648 - [std.variant.Variant] Incorrectly written unittests
  std/variant.d
Labels: Bug Fix, auto-merge

#8352 ✏️ fix typos in docs
  std/format/package.d
Labels: auto-merge

#8336 Fix issue 22532 - change default log level to LogLevel.warning
  changelog/logger_default_warning.dd
  std/experimental/logger/core.d
  std/experimental/logger/filelogger.d
  std/experimental/logger/multilogger.d
Labels: Enhancement, auto-merge

#8355 Cherry-pick Azure upgrade to master
  azure-pipelines.yml
Labels: auto-merge, Continuous Integration

#8354 std.stdio: clarify "not opened" documentation
  std/stdio.d
Labels: auto-merge

#8360 add isSomeFiniteCharInputRange as simplification
  std/conv.d
  std/file.d
  std/json.d
  std/path.d
  std/process.d
  std/range/package.d
  std/stdio.d
  std/utf.d
Labels: auto-merge

#6876 Also expose 'parent' when it's abstract
  std/typecons.d
Labels: auto-merge

#8361 Fix issue 14892: std.array.array support for -profile=gc.
  std/array.d
Labels: WIP, Enhancement

#8100 Move checkedint out of experimental
  .dscanner.ini
  changelog/checkedint.dd
  dub.sdl
  index.dd
  posix.mak
  std/checkedint.d
  std/experimental/checkedint.d
  std/file.d
  win32.mak
  win64.mak
Labels: auto-merge-squash

#8367 Make win32.mak compatible with MODEL=32omf
  azure-pipelines.yml
  win32.mak
Labels: Continuous Integration

#8366 Fix Issue 22704 - Linker error when running the public unittests
  posix.mak
  std/complex.d
  std/traits.d
Labels: Blocking Other Work, Bug Fix, auto-merge

#8362 Changed chooseAmong implementation from recursive to linear.
  std/range/package.d
Labels: auto-merge

#8359 Fixes issues 22185, 22673
  std/array.d
Labels: Bug Fix, auto-merge-squash

#8369 std.traits: add examples
  std/traits.d
Labels: auto-merge

#8365 Fix Issue 22695 - std.traits.isBuiltinType is false for typeof(null)
  std/traits.d
Labels: Bug Fix

#8364 Fix issue 22701: Remove is(typeof()) callable check in std.typecons.apply.
  std/typecons.d
Labels: Bug Fix, Enhancement
