Repository dlang/phobos, pull requests merged in 2023-04, with the labels that each got.

#8730 purge changelog
  changelog/grapheme_walker_update.dd
  changelog/joiner_assert_message.dd
  changelog/sort_assert_messaged.dd
Labels: auto-merge

#8731 Add bind to the header table
  std/functional.d
Labels: auto-merge

#8733 merge stable
  std/functional.d
Labels: stable -> master

#8722 Feature: Implement Rebindable for non-class/non-array types.
  changelog/rebindable_all_types.dd
  std/typecons.d
Labels: auto-merge

#8737 Fix issue 22785: `joiner` should `Unqual` child ranges.
  std/algorithm/iteration.d
Labels: Bug Fix, auto-merge-squash

#8734 Fix issue 22786 (immutable element in maxElement) by always using Rebindable.
  std/algorithm/searching.d
  std/typecons.d
Labels: Bug Fix, auto-merge

#8741 clarify documentation for std.traits.isIntegral
  std/traits.d
Labels: documentation, Easy Review

#8738 Fix issue 16942: slide!(No.withPartial): Correctly handle first slide exhausting input range.
  std/range/package.d
Labels: Bug Fix, Enhancement
