Repository dlang/phobos, pull requests merged in 2023-10, with the labels that each got.

#8829 Adjust conditions in putChar to avoid declaring static symbol
  std/range/primitives.d
Labels: Easy Review, Refactoring

#8828 Add std.traits.isQualifierConvertible
  std/traits.d
Labels: auto-merge, 72h no objection -> merge

#8831 CI: Move Cirrus jobs to GitHub Actions
  .cirrus.yml
  .github/workflows/main.yml
Labels: auto-merge, Continuous Integration

#8833 Typo
  std/parallelism.d
Labels: auto-merge

#8834 make std.parallelism.AbstractTask inaccessible
  std/parallelism.d
Labels: Bug Fix

#8835 Revert "GHA: Work around a `$p:`bug in DMD's d_do_test.d"
  .github/workflows/main.yml
Labels: auto-merge

#8830 Use isQualifierConvertible in isInputRange!(R, E)
  .dscanner.ini
  std/range/primitives.d
Labels: auto-merge

#8837 Add Unshared to std.traits.
  changelog/unshared.dd
  std/traits.d
Labels: auto-merge, Atila Neves
