Repository dlang/phobos, pull requests merged in 2023-07, with the labels that each got.

#8776 merge stable
  std/algorithm/searching.d
  std/range/package.d
Labels: Bug Fix, auto-merge, stable -> master

#8779 Fix issue 24028 - BigInt power operator ignores sign of exponent
  std/bigint.d
Labels: Bug Fix

#8777 Fix issue 24027: Instead of a bunch of special-cases, just check that `Rebindable` did in fact alias itself away.
  std/algorithm/searching.d
Labels: Bug Fix, auto-merge

#8778 Add warning to std.json that it doesn't play well with the GC.
  std/json.d
Labels: auto-merge

#8780 Remove declarations with expired deprecations
  std/math/package.d
  std/stdio.d
Labels: auto-merge, Easy Review, Deprecation

#8782 merge stable
  std/algorithm/searching.d
Labels: Bug Fix, stable -> master

#8784 Fix 24049 - std.conv.to: string to enum conversion is not documented
  std/conv.d
Labels: documentation, Bug Fix
