Repository dlang/phobos, pull requests merged in 2023-06, with the labels that each got.

#8762 std.path.absolutePath: make compatible with scope and preview='in'
  std/path.d
Labels: auto-merge

#8765 merge stable
  std/regex/internal/ir.d
Labels: stable -> master

#8763 fix issue 23361 - std.uni.normalize made pure
  std/uni/package.d
Labels: Bug Fix

#8771 std.stdio: add default case
  std/stdio.d
Labels: auto-merge, Easy Review

#8770 fix Issue 23312 - Crash when calling writeln in WinMain
  std/stdio.d
Labels: Bug Fix

#8772 std.stdio: add glossary, fileno_t
  std/stdio.d
Labels: documentation

#8767 Fix Issue 23997 - isClose(1, -double.infinity) returns true
  std/math/operations.d
Labels: Bug Fix

#8773 Fix issue 23976: std.range.slide fails in dmd-2.104.0
  std/range/package.d
Labels: Bug Fix

#8764 Fix issue 23993: Discard Rebindable before passing extremum to compar…
  std/algorithm/searching.d
Labels: Bug Fix
