Repository dlang/phobos, pull requests merged in 2023-12, with the labels that each got.

#8858 merge stable
  changelog/PR8804.dd
  changelog/is_input_range_element.dd
  changelog/unshared.dd
  std/uni/package.d
Labels: Bug Fix

#8861 Update math.algebraic.d#abs to return correct integral type
  std/math/algebraic.d
Labels: Bug Fix

#8868 Makefile: Slightly simplify recursive make invocations
  Makefile
Labels: auto-merge

#8866 Fix issue 24075 - Can't use toChars with `ushort` or `ubyte`
  std/conv.d
Labels: Enhancement
