Repository dlang/phobos, pull requests merged in 2023-09, with the labels that each got.

#8807 Create PR8804.dd
  changelog/PR8804.dd
Labels: auto-merge

#8808 Improve documentation in std.json and std.socket
  std/json.d
  std/socket.d
Labels: auto-merge

#8809 Fix Issue 24140 - Int128.opBinary [+-*/%&|^] with negative long arguments gives wrong answers
  std/int128.d
Labels: Bug Fix, auto-merge

#8816 merge stable
  std/int128.d
Labels: Bug Fix

#8810 Fix Issue 24142 - Allow casting Int128 to integral and floating types
  std/int128.d
Labels: Enhancement
