Repository dlang/phobos, pull requests merged in 2023-08, with the labels that each got.

#8791 Fix issue 24064: use consistent types for ResultRanges.
  std/range/package.d
Labels: Bug Fix

#8796 [std/array] Split staticArray docs into two groups
  std/array.d
Labels: auto-merge

#8795 [std/exception] Tweak docs
  std/exception.d
Labels: auto-merge

#8799 Fix hang in SHA code with buffer > 4gb
  std/digest/sha.d
Labels: auto-merge

#8800 merge stable
  std/range/package.d
Labels: Bug Fix, auto-merge

#8801 Cross-link to std.mathspecial.
  std/math/package.d
Labels: documentation, Trivial, auto-merge

#8797 Fix Issue 24082 - add Int128.toString that supports std.format
  std/int128.d
Labels: Enhancement

#8798 Fix Issue 24083 - Int128.opCmp's behavior with negative numbers is inconsistent with Int128.opEquals
  std/int128.d
Labels: Bug Fix

#8803 std.stdio: untangle fdopen references
  std/stdio.d
Labels: auto-merge, Easy Review, Refactoring

#8802 std.stdio: remove redundant version declarations
  std/stdio.d
Labels: Easy Review, Refactoring
