Repository dlang/phobos, pull requests merged in 2023-02, with the labels that each got.

#8675 merge stable
  changelog/log_float_double_implementations.dd
  changelog/unicode_properties_c.dd
  changelog/unicode_table_generator.dd
  changelog/unique-struct-dtor.dd
  std/typecons.d
Labels: Bug Fix, auto-merge

#8676 Fix issue 23668: TimSort must avoid default initialization if the type being sorted has it disabled.
  std/algorithm/sorting.d
Labels: Bug Fix, auto-merge

#8677 Better document the use of Heaps with Dynamic Array as Store
  std/container/binaryheap.d
Labels: Bug Fix, auto-merge-squash

#8683 Fix issue 23668: TimSort must avoid default initialization if the type being sorted has it disabled.
  std/algorithm/sorting.d
Labels: Bug Fix, auto-merge, stable -> master

#8679 Fix Issue 23683 - std.file.setTimes requests more permissions than needed
  std/file.d
Labels: Enhancement

#8684 Fix Issue 23706 - Do not escape POSIX shell parameters unless necessary
  std/process.d
Labels: Enhancement

#8686 Update dscanner to v0.14.0
  posix.mak
Labels: auto-merge

#8688 std.net.curl: add missing import to examples
  std/net/curl.d
Labels: Bug Fix, auto-merge

#8689 Tweak std.traits categories
  std/traits.d
Labels: auto-merge

#8691 More avoidance of std.traits.ReturnType
  std/range/primitives.d
  std/traits.d
Labels: auto-merge-squash

#8690 algorithm/sorting: Fix typo introduced in PR #8678
  std/algorithm/sorting.d
Labels: auto-merge

#8693 std.math.exponential: Fix log10 coefficient order
  std/math/exponential.d
Labels: math, auto-merge, Regression

#8695 Memory leak on std.process
  std/process.d
Labels: auto-merge

#8681 std.socket - tired of heisenbug failures in test suite
  std/socket.d
Labels: Easy Review

#8697 merge stable
  std/math/exponential.d
Labels: auto-merge, stable -> master

#8702 Change how preview=in is detected
  std/format/internal/write.d
Labels: auto-merge

#8703 Change a unittest in std.traits for upcoming deprecation
  std/traits.d
Labels: auto-merge
