Repository dlang/phobos, pull requests merged in 2023-05, with the labels that each got.

#8721 fix 14478: support non-copyable elements in many range algorithms
  std/range/package.d
Labels: Enhancement, auto-merge

#8749 std.conv handle default integer-to-string with core.internal.string
  std/conv.d
Labels: auto-merge, Easy Review

#8744 fix issue 23881: add std.system.instructionSetArchitecture and std.system.ISA
  changelog/std_system_instruction_set_architecture.dd
  std/system.d
Labels: Enhancement, Atila Neves

#8736 Fix issue 23844: Support ranges with immutable fields (like `only` with `immutable struct`) in `chain`.
  std/range/package.d
Labels: Bug Fix

#8754 delete unused overload of std.conv.convError()
  std/conv.d
Labels: auto-merge, Easy Review, Refactoring

#8755 std.conv integer to string: use core.internal.string
  std/conv.d
Labels: Easy Review

#8756 std.path.expandTilde: make compatible with scope and preview='in'
  std/path.d
Labels: auto-merge

#8757 Better std.algorithm.iteration.permutations error messages
  changelog/permutation_assert_message.dd
  std/algorithm/iteration.d
Labels: auto-merge

#8759 Fix Issue 23940 - std.getopt does not assert with options that only d…
  std/getopt.d
Labels: Bug Fix, auto-merge

#8760 Don't use this in static context in std.range.package
  std/range/package.d
Labels: auto-merge
