Repository dlang/phobos, pull requests merged in 2024-10, with the labels that each got.

#9048 std/process: Default to libc closefrom in spawnProcessPosix
  std/process.d
Labels: Bug Fix

#9056 Fix issue 24801 - `RefRange` doesn’t work if range primitives are not `const`
  std/range/package.d
Labels: Bug Fix, 72h no objection -> merge

#9057 Fix bugzilla issue 24809: In some cases, stable sort assigns to unininitialized elements
  std/algorithm/sorting.d
Labels: Bug Fix, 72h no objection -> merge

#8951 co-locate overloads of std.algorithm.mutation.swap()
  std/algorithm/mutation.d
Labels: Easy Review, Refactoring

#9060 fix long line linter error
  std/range/package.d
Labels: Trivial

#9065 Fix issue 24824 - ensure we exit a child that does not succeed in exec.
  std/process.d
Labels: Bug Fix

#9064 Fix Issue 24823 - std.json: Allow optionally preserving the order of fields in JSON objects
  std/json.d
Labels: Enhancement

#9068 Add Phobos 3 Documentation
  phobos/CONTRIBUTING.md
  phobos/Design.md
  phobos/PackageMap.md
  phobos/README.md
Labels: Phobos 3

#9069 Remove Phobos 3 dub.sdl and replace it with the build_v3.d build script.
  .gitignore
  build_v3.d
  dub.sdl
Labels: Phobos 3

#8560 overhaul documentation of std.string indexOf-like functions
  std/string.d
Labels: Salvage

#8576 chore(allocator): make AlignedMallocator pure
  std/experimental/allocator/mallocator.d
Labels: auto-merge-squash

#9067 Fix Bugzilla issue 24827: maxElement does not handle opAssign correctly.
  std/algorithm/searching.d
  std/typecons.d
Labels: Bug Fix

#9073 Fix bugzilla issue 24637
  std/container/dlist.d
Labels: Bug Fix, auto-merge

#8822 Simplify endian conversion functions in std.bitmanip.
  std/bitmanip.d
Labels: auto-merge-squash

#8596 Add AllocatorState
  std/experimental/allocator/common.d
Labels: auto-merge

#9075 Fix UndocumentedDeclarationCheck linting issue in typecons.d
  std/typecons.d
Labels: auto-merge

#9076 [stable] Cherry-pick 2 master fixes
  std/algorithm/sorting.d
Labels: Bug Fix, auto-merge
