Repository dlang/phobos, pull requests merged in 2024-08, with the labels that each got.

#9039 Fix Bugzilla 22293: opCast!bool for Nullable
  std/typecons.d
Labels: Enhancement

#9031 Fix issue 24686: SumType stopped working with unmatched DeducedParame…
  std/traits.d
Labels: Bug Fix, Industry

#9044 Fix Bugzilla 24698 - Appender needs to expose readonly property 'size…
  std/array.d
Labels: Enhancement, auto-merge

#9047 Fix issue 24704: Improve error messages for from*String in std.datetime.
  std/datetime/date.d
  std/datetime/systime.d
Labels: Bug Fix, auto-merge

#9043 Issue 24095 - std.bitmanip.bitfields no longer works with bool enum t…
  std/bitmanip.d
Labels: Bug Fix
