Repository dlang/phobos, pull requests merged in 2024-09, with the labels that each got.

#9050 graphemeStride now @nogc with DChars
  std/uni/package.d
Labels: auto-merge

#9049 Fix Bugzilla 24773: don't invoke destructors on uninitialized elements in stable sort
  std/algorithm/sorting.d
Labels: Bug Fix, auto-merge

#9052 Remove -de switch from Phobos builds to allow deprecations.
  Makefile
Labels: auto-merge-squash
