Repository dlang/phobos, pull requests merged in 2024-05, with the labels that each got.

#8997 Fix documentation typos.
  std/logger/core.d
Labels: auto-merge

#8998 merge stable
  std/logger/core.d
  std/range/package.d
Labels: Bug Fix

#8993 Remove OMF flags from Makefile
  Makefile
Labels: Deprecation, Continuous Integration

#9000 std/math/hardware.d: Fix compile error for LoongArch
  std/math/hardware.d
Labels: auto-merge

#9002 Fix issue 24549 - std.process.environment.get(null) segfaults
  std/process.d
Labels: Bug Fix, auto-merge

#9004 Fix Bugzilla 24564 - std.file.DirEntry throws Exception instead of Fi…
  std/file.d
Labels: Bug Fix, auto-merge

#9005 Get rid of obsolete `CRuntime_DigitalMars` support
  std/experimental/allocator/mallocator.d
  std/math/rounding.d
  std/process.d
  std/stdio.d
Labels: auto-merge

#9006 merge stable
  std/process.d
Labels: Bug Fix
