Repository dlang/phobos, pull requests merged in 2024-04, with the labels that each got.

#8965 Fix alignment of buffers in kernighan_ritchie unittests.
  std/experimental/allocator/building_blocks/kernighan_ritchie.d
Labels: Bug Fix, auto-merge

#8963 Fix bugzilla #24465: Make Tuple work with copy constructors
  std/typecons.d
Labels: Bug Fix, auto-merge

#8966 merge stable
  changelog/range_predicate_element.dd
  changelog/upgrade-unicode.dd
  std/experimental/allocator/building_blocks/kernighan_ritchie.d
  std/net/curl.d
  std/typecons.d
Labels: Bug Fix

#8970 Add isEqual and EnumMembers to phobos.sys.traits.
  phobos/sys/traits.d
Labels: Phobos 3

#8974 Add lvalueOf and rvalueOf to phobos.sys.traits.
  phobos/sys/traits.d
Labels: auto-merge, Phobos 3

#8973 Adds Instantiate, ApplyLeft, and ApplyRight to phobos.sys.meta.
  phobos/sys/meta.d
  phobos/sys/traits.d
Labels: auto-merge, Phobos 3

#8924 Work around bugzilla issue 24415 - only doesn't work with elements with a copy constructor.
  std/internal/test/range.d
  std/range/package.d
Labels: Bug Fix, auto-merge

#8977 Add And, Not, and Or to phobos.sys.meta.
  phobos/sys/meta.d
Labels: Phobos 3

#8978 Add OriginalType, KeyType, and ValueType to phobos.sys.traits.
  phobos/sys/traits.d
Labels: Phobos 3

#8982 Add `@nogc nothrow` to randomUUID
  std/uuid.d
Labels: auto-merge

#8983 [std.net.isemail] Fix foreach ref index
  std/net/isemail.d
Labels: auto-merge

#8981 Add isAggegregateType and isInstantiationOf to phobos.sys.traits.
  phobos/sys/traits.d
Labels: Phobos 3

#8984 Fix broken links in std.range.chain
  std/range/package.d
Labels: auto-merge

#8986 Add FieldNames, FieldSymbols, and FieldTypes to phobos.sys.traits.
  phobos/sys/traits.d
Labels: Phobos 3

#8992 Add DUB install to VM initialization.
  .github/workflows/main.yml
Labels: Phobos 3

#8969 Fix bugzilla issue 24481: retro stopped working
  std/range/package.d
Labels: Bug Fix, auto-merge
