Repository dlang/phobos, pull requests merged in 2024-02, with the labels that each got.

#8909 CheckBy postblit should be scope
  std/algorithm/iteration.d
Labels: Blocking Other Work, auto-merge

#8910 Allow assignment of std.range.only elements
  std/range/package.d
Labels: Enhancement, auto-merge

#8916 gha: Update cross-platform-actions to v0.23.0
  .github/workflows/main.yml
Labels: Easy Review, Continuous Integration

#8917 fix Bugzilla Issue 24403 - Nullable doesn't work with non-mutable types with a destructor
  std/typecons.d
Labels: Bug Fix

#8918 Fix bugzilla issue 24389 - Make Phobos compile on FreeBSD 14 again.
  Makefile
Labels: Bug Fix
