Repository dlang/phobos, pull requests merged in 2024-03, with the labels that each got.

#8933 sumtype: add hint to "never matches" message
  std/sumtype.d
Labels: auto-merge

#8935 std.range.choose: call payload postblit correctly
  std/range/package.d
Labels: Bug Fix, auto-merge

#8936 [trivial] std.path: Note that absolutePath and co. do not collapse ".."
  std/path.d
Labels: Trivial

#8938 Add ConstOf, ImmutableOf, InoutOf, and SharedOf to lib.sys.traits.
  lib/sys/traits.d
Labels: auto-merge, Phobos 3

#8939 Add isDynamicArray and isStaticArray to lib.sys.traits.
  lib/sys/traits.d
Labels: Phobos 3

#8940 Add isSomeString and isSomeChar to lib.sys.traits.
  lib/sys/traits.d
Labels: Phobos 3

#8942 Remove isSomeString and isSomeChar.
  lib/sys/traits.d
Labels: Phobos 3

#8945 Add isInteger and isFloatingPoint to lib.sys.traits.
  lib/sys/traits.d
Labels: Phobos 3

#8943 use cast() where we can
  std/bitmanip.d
  std/conv.d
  std/math/algebraic.d
  std/variant.d
Labels: Easy Review, Refactoring

#8944 utf.d replace use of Unqual with cast()
  std/utf.d
Labels: Easy Review, Refactoring

#8946 Add isNumeric and isPointer.
  lib/sys/traits.d
Labels: Phobos 3

#8947 Rearrange some code in lib.sys.traits.
  lib/sys/traits.d
Labels: auto-merge-squash, Phobos 3

#8949 [std.socket] Cast assign to getaddrinfoPointer is not @safe
  std/socket.d
Labels: auto-merge

#8948 Rename lib.sys.traits' Unqual to Unqualified.
  lib/sys/meta.d
  lib/sys/traits.d
Labels: auto-merge, Phobos 3

#8952 Remove explicit hex string casts
  std/internal/unicode_comp.d
  std/internal/unicode_decomp.d
  std/internal/unicode_grapheme.d
  std/internal/unicode_norm.d
  std/internal/unicode_tables.d
  tools/unicode_table_generator.d
Labels: auto-merge, Refactoring

#8950 swap-and-destroy called too eagerly
  std/typecons.d
Labels: Blocking Other Work

#8953 Rename lib to phobos.
  dub.sdl
  lib/package.d
  lib/sys/package.d
  phobos/sys/compiler.d
  phobos/sys/meta.d
  phobos/sys/system.d
  phobos/sys/traits.d
Labels: Phobos 3

#8954 Add isSignedInteger and isUnsignedInteger to phobos.sys.traits.
  phobos/sys/traits.d
Labels: Phobos 3

#8957 Add Filter and Reverse to phobos.sys.meta.
  phobos/sys/meta.d
Labels: auto-merge, Phobos 3

#8958 std/math/hardware.d: use an alternative register naming to fix LDC compilation
  std/math/hardware.d
Labels: auto-merge

#8959 Add allSatisfy and anySatisfy to phobos.sys.meta.
  phobos/sys/meta.d
Labels: Phobos 3

#8960 Add isSameSymbol and isSameType to v3 traits and indexOf to v3 meta.
  phobos/sys/meta.d
  phobos/sys/traits.d
Labels: Phobos 3

#8962 Add Stride and Uniq to phobos.sys.meta.
  phobos/sys/meta.d
Labels: auto-merge-squash, Phobos 3

#8961 Fix Bugzilla Issue 24458 - Mac M3 associative array keys on std.net.curl gets overwritten
  std/net/curl.d
Labels: Bug Fix, auto-merge

#8964 [std.traits] Improve FunctionTypeOf docs
  std/traits.d
Labels: auto-merge
