Repository dlang/phobos, pull requests merged in 2024-01, with the labels that each got.

#8870 Revert "Makefile: Compile zlib .c files with DMD via importC"
  Makefile
  etc/c/zlib/gzwrite.c
Labels: Blocking Other Work, Regression

#8874 Fix Issue 24318 - Nullable should support non-copyable objects
  std/typecons.d
Labels: Enhancement

#8883 Remove failing FreeBSD 12 CI
  .github/workflows/main.yml
Labels: Continuous Integration

#8880 std.uni: optimize fullCaseTable
  .dscanner.ini
  std/internal/unicode_tables.d
  std/uni/package.d
  tools/unicode_table_generator.d
Labels: auto-merge

#8878 std.uni: optimize simpleCaseTable
  std/internal/unicode_tables.d
  std/uni/package.d
  tools/unicode_table_generator.d
Labels: auto-merge, Refactoring

#8887 Move floatTraits to std.math.traits
  std/complex.d
  std/conv.d
  std/math/algebraic.d
  std/math/exponential.d
  std/math/operations.d
  std/math/package.d
  std/math/rounding.d
  std/math/traits.d
  std/math/trigonometry.d
Labels: auto-merge, Refactoring

#8888 std.regex: put disassemble function in debug version
  std/regex/internal/backtracking.d
  std/regex/internal/ir.d
Labels: auto-merge, Refactoring

#8889 std.uni: Use dstring for dchar tables
  std/internal/unicode_comp.d
  std/internal/unicode_decomp.d
  std/internal/unicode_tables.d
  tools/unicode_table_generator.d
Labels: Refactoring

#8891 Fix 24339 - std.mmfile has poor documentation
  std/mmfile.d
Labels: Bug Fix, auto-merge

#8892 Fix std.mmap documentation
  std/mmfile.d
Labels: documentation, auto-merge

#8893 Fix IRC link. (Freenode is dead, #d has been on libera for years.)
  CONTRIBUTING.md
Labels: auto-merge

#8895 std.math.hardware: Remove mixin around RISCV implementations
  std/math/hardware.d
Labels: auto-merge, Easy Review

#8894 Fix issue 24342: Actually check that range and sentinel types match
  std/algorithm/searching.d
Labels: Bug Fix

#8898 Update docs for hasSlicing with inifnite range
  std/range/primitives.d
Labels: Bug Fix, auto-merge

#8899 GHA: Use all 4 new CPU cores on non-Mac runners
  .github/workflows/main.yml
Labels: auto-merge

#8902 Fix std.bitmanip.bitfields documentation
  std/bitmanip.d
Labels: auto-merge-squash

#8901 std.uni: use hex strings for TrieEntry
  std/internal/unicode_comp.d
  std/internal/unicode_decomp.d
  std/internal/unicode_grapheme.d
  std/internal/unicode_norm.d
  std/internal/unicode_tables.d
  tools/unicode_table_generator.d
Labels: auto-merge

#8905 merge stable
  std/algorithm/searching.d
Labels: Bug Fix
