Repository dlang/phobos, pull requests merged in 2024-11, with the labels that each got.

#9077 Fix bugzilla 24524: Very slow process fork if RLIMIT_NOFILE is too high
  std/process.d
Labels: Enhancement

#9080 Optimize fromHexString()
  std/digest/package.d
Labels: auto-merge

#9082 Fix 17416 - Add REUSEPORT to std.socket
  std/socket.d
Labels: Enhancement, auto-merge

#9081 Reference std.digest.fromHexString in doc of std.conv.hexString
  std/conv.d
Labels: auto-merge

#9083 Fix bugzilla 24851 - Some members of CustomFloat can have const this
  std/numeric.d
Labels: Enhancement

#9084 Fix appender code that might not initialize memory that might point at huge allocations
  std/array.d
Labels: Bug Fix

#9085 [stable] GitHub Actions: Remove macos-12 job, as the image will disappear soon
  .github/workflows/main.yml
Labels: auto-merge

#9086 Merge stable
  .github/workflows/main.yml
  std/algorithm/searching.d
  std/array.d
  std/bitmanip.d
  std/container/dlist.d
  std/logger/core.d
  std/logger/filelogger.d
  std/logger/package.d
  std/process.d
  std/traits.d
  std/typecons.d
Labels: Bug Fix, auto-merge

#9090 Fix Bugzilla issue 24875
  std/traits.d
Labels: Enhancement

#9088 Add hasComplex{Assignment,Copying,Destruction).
  phobos/sys/traits.d
Labels: Phobos 3

#9091 Add note to Unqualified about is(immutable T == immutable U).
  phobos/sys/traits.d
Labels: auto-merge, Phobos 3
