Repository dlang/phobos, pull requests merged in 2025-04, with the labels that each got.

#10739 Fix #10731 - Windows link error with std.random.uniform() in v2.111
  Makefile
  std/internal/windows/bcrypt.d
  std/random.d
Labels: Severity:Regression

#10741 `getrandom()` backwards compatibility shim
  Makefile
  std/random.d
Labels: OS:Linux

#10757 Polish `getrandom()` backwards compatibility shim
  changelog/emulate_getrandom.dd
  std/random.d
Labels: Severity:Documentation, Severity:Minor

#10752 fix: give compile error for infinite range in format
  std/format/internal/write.d
Labels: Merge:72h no objection -> merge

#10765 [stable] Revert "Add low-overhead `InPlaceAppender` (#8789)"
  std/array.d
Labels: Review:stable-priority, Severity:Regression
