Repository dlang/phobos, pull requests merged in 2025-08, with the labels that each got.

#10824 10823 fix, fixed sign of beta(x,y) when x+y large
  std/mathspecial.d
Labels: Review:Needs Review

#10848 Adds UUID v7 support
  changelog/uuidv7.dd
  std/uuid.d
Labels: Merge:auto-merge

#10853 Replace templates with templated enums in std/random.d
  std/random.d
Labels: Review:Refactoring
