Repository dlang/phobos, pull requests merged in 2025-05, with the labels that each got.

#10748 Add internal multi-backend entropy system
  .dscanner.ini
  Makefile
  changelog/entropy_system.dd
  std/internal/entropy.d
  std/random.d
Labels: Severity:Enhancement, Review:Refactoring, std.random

#10770 Add unittest from #10769
  std/file.d
Labels: Severity:Coverage

#10787 Fix #10785 - Fix invalid access of GC memory from destructor when inside a GC finalizer with debug build
  std/uni/package.d
Labels: Merge:auto-merge

#10782 conform to return-ref-scope ordering
  std/typecons.d
Labels: Review:DIP25 / DIP1000

#10789 use return scope rather than scope return
  std/typecons.d
Labels: Attributes
